file: lost_channels.py
description_ru: Скрипт для привязки потерянных каналов, в случае переподключения камер как новые IP-устройства, или в случае не удачного восстановления бэкапа.
description_en:
categories:
  - channels