from .translation_base import Translated


class EventsLoc(Translated):
    intrusion_alert = "Intrusion Alert"
    allowed_access_by_key = "Allowed Access By Key"
    door_restored = "Door Restored"
    door_broken = "Door Broken"
    door_blocked = "Door Blocked"
    no_access_to_all = "No Access To All"
    access_denied = "Access Denied %1"
    access_granted = "Access Granted %1"
    no_access = "No Access %1"
    reader_contact_lost = "Reader Contact Lost"
    walk_detected = "Walk Detected"
    free_walk_allowed = "Free Walk Allowed"
    armed = "Armed"
    left_object_detected = "Left Object Detected"
    item_abandoned = "Item Abandoned"
    item_missing = "Item Missing"
    slow_down_detected = "Slow Down Detected"
    tamper_alert = "Tamper Alert"
    tamper_alert_defocus = "Tamper Alert: Defocus"
    tamper_alert_covered = "Tamper Alert: Covered"
    tamper_alert_flashing = "Tamper Alert: Flashlight"
    tamper_alert_shift = "Tamper Alert: Shift"
    motion_start = "Motion Start"
    sound_detected = "Sound Detected"
    smoke_detected = "Smoke Detected"
    fire_detected = "Fire Detected"
    fire_stopped = "Fire Stopped"
    fire = "Fire"
    face_recognized = "Face Recognized"
    facs_1 = "FACS: %1"
    facs_disconnected = "FACS Disconnected"
    facs_connected = "FACS Connected"
    access_deny = "Deny: %1 (%2)"
    access_allow = "Allow: %1 (%2)"
    pass_through = "Pass: %1 (%2)"
    access_point_disconnected = "Access Point Disconnected"
    access_point_connected = "Access Point Connected"
    access_point_once_opened = "Access Point Once Opened"
    access_point = "Access Point: %1"
    facs_alarm = "Alarm: %1 (%2)"
    access_point_closed_to_all = "Access Point Closed To All"
    access_point_opened_to_all = "Access Point Opened To All"
    access_point_allows_by_key = "Access Point Allows By Key"

    signal_lost = "Signal Lost"
    signal_restored = "Signal Restored"

    input_operations = "Input Operations"
    crossline_detected = "CrossLine Detected"
    intrusion_detected = "Intrusion Detected"
    face_detected = "Face Detected"

    border_crossed_a_b = "Border Crossed A -> B"
    border_crossed_b_a = "Border Crossed B -> A"
    object_track_length_alarm = "Object Track Length Alarm"
    object_size_alarm = "Object Size Alarm"
    object_speed_alarm = "Object Speed Alarm"
    object_entered_the_zone = "Object Entered the Zone"
    object_left_the_zone = "Object Left the Zone"
    object_presence_alarm = "Object presence alarm"
    max_count_people = "Max count people"
    max_count_vehicles = "Max count vehicles"
    max_count_bicycles = "Max count bicycles"
    input_high_to_low_event = "Input High to Low"
    input_low_to_high_event = "Input Low to High"
    orion_disconnected = "Orion Disconnected"
    person_without_helmet_detected = "Person without helmet detected"
    person_without_uniform_detected = "Person without uniform detected"
    warning_thermal_signal = "Warning: Thermal Signal"
    plate_detected = "Plate detected"
    people_detected_neuro = "People Detected"
    aruco_entered_the_zone = "Aruco entered the zone"
    aruco_left_the_zone = "Aruco left the zone"

    # GATE EVENTS
    legal_card_authentication_passed = "Legal card authentication passed: %1"
    controller_disconnected = "Controller Disconnected"
    controller_connected = "Controller Connected"
    controller_proc_1 = "Controller: %1"
    invalid_card = "Invalid card: %1"
    controller_alarm_proc_1 = "Controller Alarm: %1"

    voron_event = "VORON event"
    person_without_mask_found = "Person without mask found"
    social_distance_violation_detected = "Social distance violation detected"
    suspicious_pose = "Suspicious pose"
