file: face_from_folder_2.0-release.py
description_ru: Добавление персон из заранее подготовленных фотографий с сохранением структуры и имён папок в базу лиц. Выгрузка из базы лиц с сохранением структуры и имён папок.
description_en:
categories:
  - fr
  - persons