# 551 icons in 34 categories, generated at 2020-06-05


class Aruco(object):
    detection = ":/aruco/aruco-detection.png"


class Fortnet(object):
    logo = ":/fortnet/fortnet-logo.png"


class Pos(object):
    robot_3 = ":/pos/pos-robot-3.png"


class Sphinx(object):
    logo = ":/sphinx/sphinx-logo.png"


class Fmgr(object):
    sort = ":/fmgr/fmgr-sort.png"
    tile = ":/fmgr/fmgr-tile.png"


class Pvr(object):
    groups_horizontal = ":/pvr/pvr-groups-horizontal.png"
    groups_vertical = ":/pvr/pvr-groups-vertical.png"


class Tabs(object):
    tab_close_hovered = ":/tabs/tab-close-hovered.png"
    tab_close = ":/tabs/tab-close.png"


class Fancylog(object):
    arrow_down = ":/fancylog/fancylog-arrow-down.png"
    arrow_up = ":/fancylog/fancylog-arrow-up.png"
    flag = ":/fancylog/fancylog-flag.png"


class Auto(object):
    blacklist = ":/auto/blacklist.png"
    goes_down = ":/auto/goes_down.png"
    goes_up = ":/auto/goes_up.png"
    infolist = ":/auto/infolist.png"
    whitelist = ":/auto/whitelist.png"


class Stemax(object):
    device_gray = ":/stemax/stemax-device-gray.png"
    device_ok = ":/stemax/stemax-device-ok.png"
    device_red = ":/stemax/stemax-device-red.png"
    gray = ":/stemax/stemax-gray.png"
    ok = ":/stemax/stemax-ok.png"


class Facer(object):
    comment = ":/facer/comment.png"
    edit = ":/facer/edit.png"
    face_recognizer = ":/facer/face-recognizer.png"
    crown_gray_16 = ":/facer/icons/crown-gray-16.png"
    crown_yellow_16 = ":/facer/icons/crown-yellow-16.png"
    trash = ":/facer/trash.png"


class Gui(object):
    filter16 = ":/gui/gui-filter16.png"
    mark16 = ":/gui/gui-mark16.png"
    options16 = ":/gui/gui-options16.png"
    search_noshadow16 = ":/gui/gui-search-noshadow16.png"
    search_white16 = ":/gui/gui-search-white16.png"
    search16 = ":/gui/gui-search16.png"


class Merge(object):
    back_button = ":/merge/back-button.png"
    disabled_block = ":/merge/disabled-block.png"
    edit_channel = ":/merge/edit-channel.png"
    empty_block = ":/merge/empty-block.png"
    main_block = ":/merge/main-block.png"
    subs_block = ":/merge/subs-block.png"


class Schrack(object):
    alarm_button_gray = ":/schrack/alarm-button-gray.png"
    alarm_button_green = ":/schrack/alarm-button-green.png"
    alarm_button_red = ":/schrack/alarm-button-red.png"
    smoke_detector_gray = ":/schrack/smoke-detector-gray.png"
    smoke_detector_green = ":/schrack/smoke-detector-green.png"
    smoke_detector_red = ":/schrack/smoke-detector-red.png"


class Alarms(object):
    cancelled_12 = ":/alarms/alarm-cancelled-12.png"
    cancelled_16 = ":/alarms/alarm-cancelled-16.png"
    confirmed_12 = ":/alarms/alarm-confirmed-12.png"
    confirmed_16 = ":/alarms/alarm-confirmed-16.png"
    downloading = ":/alarms/alarm-downloading.png"
    alarm = ":/alarms/alarm.png"
    paperclip = ":/alarms/alarms-paperclip.png"


class Users(object):
    user1 = ":/users/user1E.png"
    user2 = ":/users/user2E.png"
    user3 = ":/users/user3E.png"
    user4 = ":/users/user4E.png"
    user5 = ":/users/user5E.png"
    user6 = ":/users/user6E.png"
    user7 = ":/users/user7E.png"
    user8 = ":/users/user8E.png"


class Archer(object):
    bracelet = ":/archer/bracelet.png"
    connected = ":/archer/connected.png"
    disconnected = ":/archer/disconnected.png"
    exit_board = ":/archer/exit_board.png"
    firedetector = ":/archer/firedetector.png"
    gercon = ":/archer/gercon.png"
    manualfirealarm = ":/archer/manualfirealarm.png"
    speaker = ":/archer/speaker.png"
    unknown = ":/archer/unknown.png"


class Persons(object):
    folder_black = ":/persons/icons/folder-black.png"
    folder_blue = ":/persons/icons/folder-blue.png"
    folder_green = ":/persons/icons/folder-green.png"
    folder_red = ":/persons/icons/folder-red.png"
    person_add_green = ":/persons/icons/person-add-green.png"
    persons_photo_add = ":/persons/icons/persons-photo-add.png"
    persons_photo_delete = ":/persons/icons/persons-photo-delete.png"
    persons_photo_edit = ":/persons/icons/persons-photo-edit.png"
    treeview_folder_collapse_black = ":/persons/icons/treeview-folder-collapse-black.png"
    treeview_folder_expand_black = ":/persons/icons/treeview-folder-expand-black.png"


class Panel(object):
    close_window_active = ":/panel/close-window-active.png"
    close_window_disabled = ":/panel/close-window-disabled.png"
    close_window_high = ":/panel/close-window-high.png"
    close_window_norm = ":/panel/close-window-norm.png"
    close_window_white_high = ":/panel/close-window-white-high.png"
    close_window_white = ":/panel/close-window-white.png"
    empty = ":/panel/empty.png"
    menu_down_arrow_hover = ":/panel/menu-down-arrow-hover.png"
    menu_down_arrow = ":/panel/menu-down-arrow.png"
    menu_up_arrow_hover = ":/panel/menu-up-arrow-hover.png"
    menu_up_arrow = ":/panel/menu-up-arrow.png"


class Paradox(object):
    area_alarm = ":/paradox/area-alarm.png"
    area_armed_sleep = ":/paradox/area-armed-sleep.png"
    area_armed = ":/paradox/area-armed.png"
    area_disarm = ":/paradox/area-disarm.png"
    area_ready = ":/paradox/area-ready.png"
    zone_alarm = ":/paradox/zone-alarm.png"
    zone_bypass = ":/paradox/zone-bypass.png"
    zone_close = ":/paradox/zone-close.png"
    zone_memory = ":/paradox/zone-memory.png"
    zone_open = ":/paradox/zone-open.png"
    zone_trouble = ":/paradox/zone-trouble.png"


class Simt(object):
    simt_blackzone_error = ":/simt/simt-blackzone-error.png"
    simt_blackzone = ":/simt/simt-blackzone.png"
    simt_border_alert = ":/simt/simt-border-alert.png"
    simt_border_crossing = ":/simt/simt-border-crossing.png"
    simt_border_error = ":/simt/simt-border-error.png"
    simt_border = ":/simt/simt-border.png"
    simt_object_in_zone = ":/simt/simt-object-in-zone.png"
    simt_object_removed = ":/simt/simt-object-removed.png"
    simt_zone_alert = ":/simt/simt-zone-alert.png"
    simt_zone_error = ":/simt/simt-zone-error.png"
    simt_zone = ":/simt/simt-zone.png"


class Lpr(object):
    activate = ":/lpr/activate.png"
    calendar = ":/lpr/calendar.png"
    deactivate = ":/lpr/deactivate.png"
    edit = ":/lpr/edit.png"
    export = ":/lpr/export.png"
    import_ = ":/lpr/import.png"
    lpr = ":/lpr/lpr.png"
    menu_activated = ":/lpr/menu-activated.png"
    menu = ":/lpr/menu.png"
    remove = ":/lpr/remove.png"
    search = ":/lpr/search.png"
    shopping_list_2 = ":/lpr/shopping-list-2.png"
    trash = ":/lpr/trash.png"


class Te(object):
    active = ":/te/te-active.png"
    car_dot_dot_dot = ":/te/te-car-dot-dot-dot.png"
    car_excl = ":/te/te-car-excl.png"
    car = ":/te/te-car.png"
    cart = ":/te/te-cart.png"
    cms = ":/te/te-cms.png"
    face = ":/te/te-face.png"
    html = ":/te/te-html.png"
    map = ":/te/te-map.png"
    phone = ":/te/te-phone.png"
    pos_expert = ":/te/te-pos-expert.png"
    pos_live = ":/te/te-pos-live.png"
    pvr = ":/te/te-pvr.png"
    sshot = ":/te/te-sshot.png"


class States(object):
    cms_sound_loud = ":/states/cms-sound-loud.png"
    cms_sound_silent = ":/states/cms-sound-silent.png"
    hdd_error = ":/states/hdd-error.png"
    hdd_ok = ":/states/hdd-ok.png"
    recording_hw = ":/states/recording-hw.png"
    recording = ":/states/recording.png"
    shelf = ":/states/shelf.png"
    shelf0 = ":/states/shelf0.png"
    shelf1 = ":/states/shelf1.png"
    shelf2 = ":/states/shelf2.png"
    shelf3 = ":/states/shelf3.png"
    shelf4 = ":/states/shelf4.png"
    shelf5 = ":/states/shelf5.png"
    ui_zzz = ":/states/ui-zzz.png"
    ui = ":/states/ui.png"


class Sip(object):
    abandomed = ":/sip/sip/abandomed.png"
    abandomed_small = ":/sip/sip/abandomed_small.png"
    clear = ":/sip/sip/clear.png"
    clear_high = ":/sip/sip/clear_high.png"
    clear_press = ":/sip/sip/clear_press.png"
    dnd = ":/sip/sip/dnd.png"
    down_arrow = ":/sip/sip/down-arrow.png"
    free = ":/sip/sip/free.png"
    incoming = ":/sip/sip/incoming.png"
    incoming_small = ":/sip/sip/incoming_small.png"
    outcoming = ":/sip/sip/outcoming.png"
    outcoming_small = ":/sip/sip/outcoming_small.png"
    phone_bad = ":/sip/sip/phone_bad.png"
    phone_good = ":/sip/sip/phone_good.png"
    smartphone = ":/sip/sip/smartphone.png"
    up_arrow = ":/sip/sip/up-arrow.png"
    whiteclose = ":/sip/sip/whiteclose.png"


class Forms(object):
    checkbox_checked_disabled = ":/forms/checkbox-checked-disabled.png"
    checkbox_checked_high = ":/forms/checkbox-checked-high.png"
    checkbox_checked = ":/forms/checkbox-checked.png"
    checkbox_disabled = ":/forms/checkbox-disabled.png"
    checkbox_high = ":/forms/checkbox-high.png"
    checkbox_indeterminate = ":/forms/checkbox-indeterminate.png"
    checkbox = ":/forms/checkbox.png"
    combo = ":/forms/combo.png"
    radio_checked_disabled = ":/forms/radio-checked-disabled.png"
    radio_checked_high = ":/forms/radio-checked-high.png"
    radio_checked = ":/forms/radio-checked.png"
    radio_disabled = ":/forms/radio-disabled.png"
    radio_high = ":/forms/radio-high.png"
    radio = ":/forms/radio.png"
    spin_down = ":/forms/spin-down.png"
    spin_left = ":/forms/spin-left.png"
    spin_right = ":/forms/spin-right.png"
    spin_up = ":/forms/spin-up.png"


class Cambar(object):
    cameras_netrec = ":/cambar/cameras-netrec.png"
    cam_amerge_err_19 = ":/cambar/cb_cam_amerge_err_19.png"
    cam_amerge_ok_19 = ":/cambar/cb_cam_amerge_ok_19.png"
    cam_amerge_record_err_19 = ":/cambar/cb_cam_amerge_record_err_19.png"
    cam_cloud_error_19 = ":/cambar/cb_cam_cloud_error_19.png"
    cam_cloud_motion_19 = ":/cambar/cb_cam_cloud_motion_19.png"
    cam_cloud_ok_19 = ":/cambar/cb_cam_cloud_ok_19.png"
    cam_cloud_record_error_19 = ":/cambar/cb_cam_cloud_record_error_19.png"
    cam_cloud_zombie_19 = ":/cambar/cb_cam_cloud_zombie_19.png"
    cam_error_19 = ":/cambar/cb_cam_error_19.png"
    cam_motion_19 = ":/cambar/cb_cam_motion_19.png"
    cam_ok_19 = ":/cambar/cb_cam_ok_19.png"
    cam_record_error_19 = ":/cambar/cb_cam_record_error_19.png"
    cam_zombie_19 = ":/cambar/cb_cam_zombie_19.png"
    folder_error_19 = ":/cambar/cb_folder_error_19.png"
    folder_expanded = ":/cambar/cb_folder_expanded.png"
    folder_motion_19 = ":/cambar/cb_folder_motion_19.png"
    folder_not_expanded = ":/cambar/cb_folder_not_expanded.png"
    folder_ok_19 = ":/cambar/cb_folder_ok_19.png"
    folder_record_error_19 = ":/cambar/cb_folder_record_error_19.png"
    folder_zombie_19 = ":/cambar/cb_folder_zombie_19.png"


class Map(object):
    access_point_washout = ":/map/access-point-washout.png"
    fac_washout = ":/map/fac-washout.png"
    grabber_washout = ":/map/grabber-washout.png"
    input_washout = ":/map/input-washout.png"
    layout_cloud_washout = ":/map/layout-cloud-washout.png"
    layout_washout = ":/map/layout-washout.png"
    orion_device_washout = ":/map/orion-device-washout.png"
    orion_key_washout = ":/map/orion-key-washout.png"
    orion_line_washout = ":/map/orion-line-washout.png"
    orion_washout = ":/map/orion-washout.png"
    output_washout = ":/map/output-washout.png"
    python_washout = ":/map/python-washout.png"
    schedule_washout = ":/map/schedule-washout.png"
    server_cloud_washout = ":/map/server-cloud-washout.png"
    server_washout = ":/map/server-washout.png"
    shelf_washout = ":/map/shelf-washout.png"
    simt_border_washout = ":/map/simt-border-washout.png"
    simt_zone_washout = ":/map/simt-zone-washout.png"
    ui_washout = ":/map/ui-washout.png"
    warning_washout = ":/map/warning-washout.png"
    warning = ":/map/warning.png"


class Facs(object):
    access_card_reader = ":/facs/fac-access-card-reader.png"
    door_armed_closed = ":/facs/fac-door-armed-closed.png"
    door_armed_opened = ":/facs/fac-door-armed-opened.png"
    door_armed_unknown = ":/facs/fac-door-armed-unknown.png"
    door_blocked_closed = ":/facs/fac-door-blocked-closed.png"
    door_blocked_opened = ":/facs/fac-door-blocked-opened.png"
    door_blocked_unknown = ":/facs/fac-door-blocked-unknown.png"
    door_disarmed_closed = ":/facs/fac-door-disarmed-closed.png"
    door_disarmed_opened = ":/facs/fac-door-disarmed-opened.png"
    door_disarmed_unknown = ":/facs/fac-door-disarmed-unknown.png"
    door_offline = ":/facs/fac-door-offline.png"
    alarm = ":/facs/facs-alarm.png"
    armed = ":/facs/facs-armed.png"
    closed = ":/facs/facs-closed.png"
    connected = ":/facs/facs-connected.png"
    controller = ":/facs/facs-controller.png"
    disconnected = ":/facs/facs-disconnected.png"
    door_armed = ":/facs/facs-door-armed.png"
    door_closed = ":/facs/facs-door-closed.png"
    door_forced = ":/facs/facs-door-forced.png"
    door_opened = ":/facs/facs-door-opened.png"
    duty = ":/facs/facs-duty.png"
    error = ":/facs/facs-error.png"
    opened = ":/facs/facs-opened.png"
    relay_off = ":/facs/facs-relay-off.png"
    relay_on = ":/facs/facs-relay-on.png"


class Other(object):
    bullet16 = ":/other/bullet16.png"
    completed = ":/other/completed.png"
    completed1 = ":/other/completed1.png"
    floor = ":/other/floor.png"
    hintmark_active = ":/other/hintmark-active.png"
    hintmark = ":/other/hintmark.png"
    layout_cloud = ":/other/layout-cloud.png"
    layout = ":/other/layout.png"
    map_analytics_inv = ":/other/map-analytics-inv.png"
    map_analytics = ":/other/map-analytics.png"
    map_dim_inv = ":/other/map-dim-inv.png"
    map_dim = ":/other/map-dim.png"
    map_people_inv = ":/other/map-people-inv.png"
    map_people = ":/other/map-people.png"
    map_ruler_inv = ":/other/map-ruler-inv.png"
    map_ruler = ":/other/map-ruler.png"
    map = ":/other/map.png"
    motion = ":/other/motion.png"
    power_off = ":/other/power-off.png"
    resetproperty = ":/other/resetproperty.png"
    settings = ":/other/settings.png"
    star_checked_high = ":/other/star-checked-high.png"
    star_checked = ":/other/star-checked.png"
    star_unchecked_high = ":/other/star-unchecked-high.png"
    star_unchecked = ":/other/star-unchecked.png"
    tooltip_triangle_left = ":/other/tooltip-triangle-left.png"
    tooltip_triangle = ":/other/tooltip-triangle.png"


class GtkIcons(object):
    add = ":/gtk-icons/gtk-add.png"
    clear = ":/gtk-icons/gtk-clear.png"
    copy = ":/gtk-icons/gtk-copy.png"
    delete = ":/gtk-icons/gtk-delete.png"
    dialog_warning16_empty = ":/gtk-icons/gtk-dialog-warning16-empty.png"
    dialog_warning16 = ":/gtk-icons/gtk-dialog-warning16.png"
    edit = ":/gtk-icons/gtk-edit.png"
    go_back_ltr = ":/gtk-icons/gtk-go-back-ltr.png"
    go_down_washout = ":/gtk-icons/gtk-go-down-washout.png"
    go_down = ":/gtk-icons/gtk-go-down.png"
    go_forward_ltr = ":/gtk-icons/gtk-go-forward-ltr.png"
    go_up_washout = ":/gtk-icons/gtk-go-up-washout.png"
    go_up = ":/gtk-icons/gtk-go-up.png"
    home = ":/gtk-icons/gtk-home.png"
    new = ":/gtk-icons/gtk-new.png"
    open = ":/gtk-icons/gtk-open.png"
    paste = ":/gtk-icons/gtk-paste.png"
    redo_ltr_disabled = ":/gtk-icons/gtk-redo-ltr-disabled.png"
    redo_ltr = ":/gtk-icons/gtk-redo-ltr.png"
    refresh = ":/gtk-icons/gtk-refresh.png"
    remove = ":/gtk-icons/gtk-remove.png"
    save_as_disabled = ":/gtk-icons/gtk-save-as-disabled.png"
    save_as = ":/gtk-icons/gtk-save-as.png"
    save_disabled = ":/gtk-icons/gtk-save-disabled.png"
    save_white_hover = ":/gtk-icons/gtk-save-white-hover.png"
    save_white = ":/gtk-icons/gtk-save-white.png"
    save = ":/gtk-icons/gtk-save.png"
    shortcut = ":/gtk-icons/gtk-shortcut.png"
    undo_ltr_disabled = ":/gtk-icons/gtk-undo-ltr-disabled.png"
    undo_ltr = ":/gtk-icons/gtk-undo-ltr.png"


class Orion(object):
    alarm_white = ":/orion/alarm-white.png"
    alarm_yellow = ":/orion/alarm-yellow.png"
    arrow_gray = ":/orion/arrow-gray.png"
    arrow_green = ":/orion/arrow-green.png"
    arrow_red = ":/orion/arrow-red.png"
    bulb_excl_gray = ":/orion/bulb-excl-gray.png"
    bulb_excl_green = ":/orion/bulb-excl-green.png"
    bulb_excl_red = ":/orion/bulb-excl-red.png"
    bulb_gray = ":/orion/bulb-gray.png"
    bulb_green = ":/orion/bulb-green.png"
    bulb_red = ":/orion/bulb-red.png"
    bulb_signal_gray = ":/orion/bulb-signal-gray.png"
    bulb_signal_green = ":/orion/bulb-signal-green.png"
    bulb_signal_red = ":/orion/bulb-signal-red.png"
    bulb_signal2_gray = ":/orion/bulb-signal2-gray.png"
    bulb_signal2_green = ":/orion/bulb-signal2-green.png"
    bulb_signal2_red = ":/orion/bulb-signal2-red.png"
    connected_gray = ":/orion/connected-gray.png"
    connected_green = ":/orion/connected-green.png"
    connected_red = ":/orion/connected-red.png"
    detached_gray = ":/orion/detached-gray.png"
    detached_green = ":/orion/detached-green.png"
    detached_red = ":/orion/detached-red.png"
    disconnected_gray = ":/orion/disconnected-gray.png"
    disconnected_green = ":/orion/disconnected-green.png"
    disconnected_red = ":/orion/disconnected-red.png"
    empty_exclamation_gray = ":/orion/empty-exclamation-gray.png"
    empty_exclamation_green = ":/orion/empty-exclamation-green.png"
    empty_exclamation_red = ":/orion/empty-exclamation-red.png"
    empty_gray = ":/orion/empty-gray.png"
    empty_green = ":/orion/empty-green.png"
    empty_red = ":/orion/empty-red.png"
    exclamation_gray = ":/orion/exclamation-gray.png"
    exclamation_green = ":/orion/exclamation-green.png"
    exclamation_red = ":/orion/exclamation-red.png"
    orion_logo = ":/orion/orion-logo.png"
    signal_gray = ":/orion/signal-gray.png"
    signal_green = ":/orion/signal-green.png"
    signal_red = ":/orion/signal-red.png"
    x_gray = ":/orion/x-gray.png"
    x_green = ":/orion/x-green.png"
    x_red = ":/orion/x-red.png"


class Settings(object):
    camera_disabled = ":/settings/camera-disabled.png"
    camera_disabledP = ":/settings/camera-disabledP.png"
    camera_error = ":/settings/camera-error.png"
    camera_errorP = ":/settings/camera-errorP.png"
    camera_netrec_off = ":/settings/camera-netrec-off.png"
    camera_netrec_offP = ":/settings/camera-netrec-offP.png"
    camera_netrec = ":/settings/camera-netrec.png"
    camera_netrecP = ":/settings/camera-netrecP.png"
    camera_zombie = ":/settings/camera-zombie.png"
    camera_zombieP = ":/settings/camera-zombieP.png"
    camera = ":/settings/camera.png"
    cameraP = ":/settings/cameraP.png"
    clear = ":/settings/clear.png"
    cloud_share = ":/settings/cloud-share.png"
    cloud_shield_16px = ":/settings/cloud-shield-16px.png"
    cloud_unshare = ":/settings/cloud-unshare.png"
    collapse = ":/settings/collapse.png"
    dead = ":/settings/dead.png"
    encryption_off = ":/settings/encryption-off.png"
    encryption_on = ":/settings/encryption-on.png"
    expand = ":/settings/expand.png"
    folder_closed = ":/settings/folder_closed.png"
    folder_opened = ":/settings/folder_opened.png"
    grabber_attention = ":/settings/grabber-attention.png"
    grabber_disabled = ":/settings/grabber-disabled.png"
    grabber_error = ":/settings/grabber-error.png"
    grabber = ":/settings/grabber.png"
    help = ":/settings/help.png"
    treeview_branch_collapsed_mouse_over = ":/settings/icons/treeview-branch-collapsed-mouse-over.png"
    treeview_branch_collapsed = ":/settings/icons/treeview-branch-collapsed.png"
    treeview_branch_expanded_mouse_over = ":/settings/icons/treeview-branch-expanded-mouse-over.png"
    treeview_branch_expanded = ":/settings/icons/treeview-branch-expanded.png"
    input_error = ":/settings/input-error.png"
    input_gray = ":/settings/input-gray.png"
    input_green_high = ":/settings/input-green-high.png"
    input_green_low = ":/settings/input-green-low.png"
    input_red_high = ":/settings/input-red-high.png"
    input_red_low = ":/settings/input-red-low.png"
    lens = ":/settings/lens.png"
    monitor = ":/settings/monitor.png"
    output_error = ":/settings/output-error.png"
    output_gray = ":/settings/output-gray.png"
    output_high = ":/settings/output-high.png"
    output_low = ":/settings/output-low.png"
    present = ":/settings/present.png"
    python_attention = ":/settings/python-attention.png"
    python_cloud_disabled = ":/settings/python-cloud-disabled.png"
    python_cloud_error = ":/settings/python-cloud-error.png"
    python_cloud = ":/settings/python-cloud.png"
    python_disabled = ":/settings/python-disabled.png"
    python_error = ":/settings/python-error.png"
    python = ":/settings/python.png"
    schedule_blue = ":/settings/schedule-blue.png"
    schedule_green = ":/settings/schedule-green.png"
    schedule_grey = ":/settings/schedule-grey.png"
    schedule_red = ":/settings/schedule-red.png"
    server_cloud = ":/settings/server-cloud.png"
    server_disabled = ":/settings/server-disabled.png"
    server_error_vtrassir = ":/settings/server-error-vtrassir.png"
    server_error = ":/settings/server-error.png"
    server = ":/settings/server.png"
    settings_blue = ":/settings/settings-blue.png"
    thermometer = ":/settings/thermometer.png"
    up_down = ":/settings/up_down.png"
    up_down_green = ":/settings/up_down_green.png"
    up_down_green_red = ":/settings/up_down_green_red.png"
    up_down_red = ":/settings/up_down_red.png"
    variable = ":/settings/variable.png"
    zip = ":/settings/zip.png"


class ArchiveCtrl(object):
    back_high_small = ":/archive-ctrl/archive-back-high-small.png"
    back_norm_small = ":/archive-ctrl/archive-back-norm-small.png"
    back_press_small = ":/archive-ctrl/archive-back-press-small.png"
    close_high_small = ":/archive-ctrl/archive-close-high-small.png"
    close_high = ":/archive-ctrl/archive-close-high.png"
    close_norm_small = ":/archive-ctrl/archive-close-norm-small.png"
    close_norm = ":/archive-ctrl/archive-close-norm.png"
    close_press_small = ":/archive-ctrl/archive-close-press-small.png"
    close_press = ":/archive-ctrl/archive-close-press.png"
    fow_high_small = ":/archive-ctrl/archive-fow-high-small.png"
    fow_norm_small = ":/archive-ctrl/archive-fow-norm-small.png"
    fow_press_small = ":/archive-ctrl/archive-fow-press-small.png"
    next_high_small = ":/archive-ctrl/archive-next-high-small.png"
    next_high = ":/archive-ctrl/archive-next-high.png"
    next_norm_small = ":/archive-ctrl/archive-next-norm-small.png"
    next_norm = ":/archive-ctrl/archive-next-norm.png"
    next_press_small = ":/archive-ctrl/archive-next-press-small.png"
    next_press = ":/archive-ctrl/archive-next-press.png"
    pause_high_small = ":/archive-ctrl/archive-pause-high-small.png"
    pause_high = ":/archive-ctrl/archive-pause-high.png"
    pause_norm_small = ":/archive-ctrl/archive-pause-norm-small.png"
    pause_norm = ":/archive-ctrl/archive-pause-norm.png"
    pause_press_small = ":/archive-ctrl/archive-pause-press-small.png"
    pause_press = ":/archive-ctrl/archive-pause-press.png"
    play_high_small = ":/archive-ctrl/archive-play-high-small.png"
    play_high = ":/archive-ctrl/archive-play-high.png"
    play_norm_small = ":/archive-ctrl/archive-play-norm-small.png"
    play_norm = ":/archive-ctrl/archive-play-norm.png"
    play_press_small = ":/archive-ctrl/archive-play-press-small.png"
    play_press = ":/archive-ctrl/archive-play-press.png"
    prev_high_small = ":/archive-ctrl/archive-prev-high-small.png"
    prev_high = ":/archive-ctrl/archive-prev-high.png"
    prev_norm_small = ":/archive-ctrl/archive-prev-norm-small.png"
    prev_norm = ":/archive-ctrl/archive-prev-norm.png"
    prev_press_small = ":/archive-ctrl/archive-prev-press-small.png"
    prev_press = ":/archive-ctrl/archive-prev-press.png"
    previewtimebg = ":/archive-ctrl/archive-previewtimebg.png"
    scroll_high_small = ":/archive-ctrl/archive-scroll-high-small.png"
    scroll_high = ":/archive-ctrl/archive-scroll-high.png"
    scroll_norm_small = ":/archive-ctrl/archive-scroll-norm-small.png"
    scroll_norm = ":/archive-ctrl/archive-scroll-norm.png"
    scroll_pf_fast_high_small = ":/archive-ctrl/archive-scroll-pf-fast-high-small.png"
    scroll_pf_fast_high = ":/archive-ctrl/archive-scroll-pf-fast-high.png"
    scroll_pf_fast_norm_small = ":/archive-ctrl/archive-scroll-pf-fast-norm-small.png"
    scroll_pf_fast_norm = ":/archive-ctrl/archive-scroll-pf-fast-norm.png"
    scroll_pf_fast_press_small = ":/archive-ctrl/archive-scroll-pf-fast-press-small.png"
    scroll_pf_fast_press = ":/archive-ctrl/archive-scroll-pf-fast-press.png"
    scroll_pf_high_small = ":/archive-ctrl/archive-scroll-pf-high-small.png"
    scroll_pf_high = ":/archive-ctrl/archive-scroll-pf-high.png"
    scroll_pf_norm_small = ":/archive-ctrl/archive-scroll-pf-norm-small.png"
    scroll_pf_norm = ":/archive-ctrl/archive-scroll-pf-norm.png"
    scroll_pf_press_small = ":/archive-ctrl/archive-scroll-pf-press-small.png"
    scroll_pf_press = ":/archive-ctrl/archive-scroll-pf-press.png"
    scroll_pf_slow_high_small = ":/archive-ctrl/archive-scroll-pf-slow-high-small.png"
    scroll_pf_slow_high = ":/archive-ctrl/archive-scroll-pf-slow-high.png"
    scroll_pf_slow_norm_small = ":/archive-ctrl/archive-scroll-pf-slow-norm-small.png"
    scroll_pf_slow_norm = ":/archive-ctrl/archive-scroll-pf-slow-norm.png"
    scroll_pf_slow_press_small = ":/archive-ctrl/archive-scroll-pf-slow-press-small.png"
    scroll_pf_slow_press = ":/archive-ctrl/archive-scroll-pf-slow-press.png"
    scroll_pr_fast_high_small = ":/archive-ctrl/archive-scroll-pr-fast-high-small.png"
    scroll_pr_fast_high = ":/archive-ctrl/archive-scroll-pr-fast-high.png"
    scroll_pr_fast_norm_small = ":/archive-ctrl/archive-scroll-pr-fast-norm-small.png"
    scroll_pr_fast_norm = ":/archive-ctrl/archive-scroll-pr-fast-norm.png"
    scroll_pr_fast_press_small = ":/archive-ctrl/archive-scroll-pr-fast-press-small.png"
    scroll_pr_fast_press = ":/archive-ctrl/archive-scroll-pr-fast-press.png"
    scroll_pr_high_small = ":/archive-ctrl/archive-scroll-pr-high-small.png"
    scroll_pr_high = ":/archive-ctrl/archive-scroll-pr-high.png"
    scroll_pr_norm_small = ":/archive-ctrl/archive-scroll-pr-norm-small.png"
    scroll_pr_norm = ":/archive-ctrl/archive-scroll-pr-norm.png"
    scroll_pr_press_small = ":/archive-ctrl/archive-scroll-pr-press-small.png"
    scroll_pr_press = ":/archive-ctrl/archive-scroll-pr-press.png"
    scroll_pr_slow_high_small = ":/archive-ctrl/archive-scroll-pr-slow-high-small.png"
    scroll_pr_slow_high = ":/archive-ctrl/archive-scroll-pr-slow-high.png"
    scroll_pr_slow_norm_small = ":/archive-ctrl/archive-scroll-pr-slow-norm-small.png"
    scroll_pr_slow_norm = ":/archive-ctrl/archive-scroll-pr-slow-norm.png"
    scroll_pr_slow_press_small = ":/archive-ctrl/archive-scroll-pr-slow-press-small.png"
    scroll_pr_slow_press = ":/archive-ctrl/archive-scroll-pr-slow-press.png"
    scroll_press_small = ":/archive-ctrl/archive-scroll-press-small.png"
    scroll_press = ":/archive-ctrl/archive-scroll-press.png"
    splitter = ":/archive-ctrl/archive-splitter.png"
    cut1_vertical = ":/archive-ctrl/cut1-vertical.png"
    cut1 = ":/archive-ctrl/cut1.png"
    cut1out_vertical = ":/archive-ctrl/cut1out-vertical.png"
    cut1out = ":/archive-ctrl/cut1out.png"
    cut2_vertical = ":/archive-ctrl/cut2-vertical.png"
    cut2 = ":/archive-ctrl/cut2.png"
    cut2out_vertical = ":/archive-ctrl/cut2out-vertical.png"
    cut2out = ":/archive-ctrl/cut2out.png"
    sound_off = ":/archive-ctrl/sound_off.png"
    sound_on = ":/archive-ctrl/sound_on.png"
