<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<!-- Automatically generated by ts_generator v1.0.0 at 2020-12-03 -->
<TS version="2.1" language="cn" sourcelanguage="en">
  <context>
    <name>AlarmMonitor</name>

    <!-- EventsLoc -->
    <message>
      <source>Access Denied %1</source>
      <translation>禁止访问 %1</translation>
    </message>
    <message>
      <source>Access Granted %1</source>
      <translation>授权访问 %1</translation>
    </message>
    <message>
      <source>Access Point Allows By Key</source>
      <translation>通过密钥访问</translation>
    </message>
    <message>
      <source>Access Point Closed To All</source>
      <translation>禁止所有访问</translation>
    </message>
    <message>
      <source>Access Point Connected</source>
      <translation>访问已连接</translation>
    </message>
    <message>
      <source>Access Point Disconnected</source>
      <translation>访问点断开</translation>
    </message>
    <message>
      <source>Access Point Once Opened</source>
      <translation>访问点单向开放</translation>
    </message>
    <message>
      <source>Access Point Opened To All</source>
      <translation>访问点全部开放</translation>
    </message>
    <message>
      <source>Access Point: %1</source>
      <translation>访问点: %1</translation>
    </message>
    <message>
      <source>Alarm: %1 (%2)</source>
      <translation>报警: %1 (%2)</translation>
    </message>
    <message>
      <source>Allow: %1 (%2)</source>
      <translation>允许: %1 (%2)</translation>
    </message>
    <message>
      <source>Allowed Access By Key</source>
      <translation>允许通过密钥访问</translation>
    </message>
    <message>
      <source>Armed</source>
      <translation>布防</translation>
    </message>
    <message>
      <source>Aruco entered the zone</source>
      <translation>Aruco 码进入区域</translation>
    </message>
    <message>
      <source>Aruco left the zone</source>
      <translation>Aruco 码离开区域</translation>
    </message>
    <message>
      <source>Border Crossed A -> B</source>
      <translation>越界 A -> B</translation>
    </message>
    <message>
      <source>Border Crossed B -> A</source>
      <translation>越界 B -> A</translation>
    </message>
    <message>
      <source>Controller Alarm: %1</source>
      <translation>控制器报警: %1</translation>
    </message>
    <message>
      <source>Controller Connected</source>
      <translation>控制器已连接</translation>
    </message>
    <message>
      <source>Controller Disconnected</source>
      <translation>控制器已断开</translation>
    </message>
    <message>
      <source>Controller: %1</source>
      <translation>控制器: %1</translation>
    </message>
    <message>
      <source>CrossLine Detected</source>
      <translation>检测到越界</translation>
    </message>
    <message>
      <source>Deny: %1 (%2)</source>
      <translation>拒绝: %1 (%2)</translation>
    </message>
    <message>
      <source>Door Blocked</source>
      <translation>门已被阻塞</translation>
    </message>
    <message>
      <source>Door Broken</source>
      <translation>门已被破坏</translation>
    </message>
    <message>
      <source>Door Restored</source>
      <translation>门已恢复</translation>
    </message>
    <message>
      <source>FACS Connected</source>
      <translation>FACS 已连接</translation>
    </message>
    <message>
      <source>FACS Disconnected</source>
      <translation>FACS 已断开</translation>
    </message>
    <message>
      <source>FACS: %1</source>
      <translation>FACS: %1</translation>
    </message>
    <message>
      <source>Face Detected</source>
      <translation>检测到人脸</translation>
    </message>
    <message>
      <source>Face Recognized</source>
      <translation>人脸被识别</translation>
    </message>
    <message>
      <source>Fire</source>
      <translation>火焰</translation>
    </message>
    <message>
      <source>Fire Detected</source>
      <translation>检测到火焰</translation>
    </message>
    <message>
      <source>Fire Stopped</source>
      <translation>火焰停止</translation>
    </message>
    <message>
      <source>Free Walk Allowed</source>
      <translation>允许任意走动</translation>
    </message>
    <message>
      <source>Input High to Low</source>
      <translation>从高到低输入</translation>
    </message>
    <message>
      <source>Input Low to High</source>
      <translation>从低到高输入</translation>
    </message>
    <message>
      <source>Input Operations</source>
      <translation>输入响应</translation>
    </message>
    <message>
      <source>Intrusion Alert</source>
      <translation>入侵报警</translation>
    </message>
    <message>
      <source>Intrusion Detected</source>
      <translation>检测到入侵</translation>
    </message>
    <message>
      <source>Invalid card: %1</source>
      <translation>未授权卡</translation>
    </message>
    <message>
      <source>Item Abandoned</source>
      <translation>物体遗留</translation>
    </message>
    <message>
      <source>Item Missing</source>
      <translation>物体消失</translation>
    </message>
    <message>
      <source>Left Object Detected</source>
      <translation>检测到遗留物</translation>
    </message>
    <message>
      <source>Legal card authentication passed: %1</source>
      <translation>授权卡认证通过: %1</translation>
    </message>
    <message>
      <source>Max count bicycles</source>
      <translation>非机动车数量超限</translation>
    </message>
    <message>
      <source>Max count people</source>
      <translation>人员数量超限</translation>
    </message>
    <message>
      <source>Max count vehicles</source>
      <translation>车辆数量超限</translation>
    </message>
    <message>
      <source>Motion Start</source>
      <translation>移动侦测开启</translation>
    </message>
    <message>
      <source>No Access %1</source>
      <translation>禁止访问 %1</translation>
    </message>
    <message>
      <source>No Access To All</source>
      <translation>所有用户禁止访问</translation>
    </message>
    <message>
      <source>Object Entered the Zone</source>
      <translation>对象进入区域</translation>
    </message>
    <message>
      <source>Object Left the Zone</source>
      <translation>对象离开区域</translation>
    </message>
    <message>
      <source>Object Size Alarm</source>
      <translation>对象尺寸报警</translation>
    </message>
    <message>
      <source>Object Speed Alarm</source>
      <translation>对象速度报警</translation>
    </message>
    <message>
      <source>Object Track Length Alarm</source>
      <translation>对象轨迹长度报警</translation>
    </message>
    <message>
      <source>Object presence alarm</source>
      <translation>对象存在警报</translation>
    </message>
    <message>
      <source>Orion Disconnected</source>
      <translation>Orion 断开</translation>
    </message>
    <message>
      <source>Pass: %1 (%2)</source>
      <translation>通过: %1 (%2)</translation>
    </message>
    <message>
      <source>People Detected</source>
      <translation>人员检测</translation>
    </message>
    <message>
      <source>Person without helmet detected</source>
      <translation>未佩戴安全帽人员</translation>
    </message>
    <message>
      <source>Person without mask found</source>
      <translation>检测到未佩戴口罩人员</translation>
    </message>
    <message>
      <source>Person without uniform detected</source>
      <translation>检测未穿工装人员</translation>
    </message>
    <message>
      <source>Plate detected</source>
      <translation>检测到车牌</translation>
    </message>
    <message>
      <source>Reader Contact Lost</source>
      <translation>读卡器断开</translation>
    </message>
    <message>
      <source>Slow Down Detected</source>
      <translation>检测到遗留物</translation>
    </message>
    <message>
      <source>Smoke Detected</source>
      <translation>检测到烟雾</translation>
    </message>
    <message>
      <source>Social distance violation detected</source>
      <translation>社交距离违反检测</translation>
    </message>
    <message>
      <source>Sound Detected</source>
      <translation>检测到噪声</translation>
    </message>
    <message>
      <source>Tamper Alert</source>
      <translation>Tamper 警告</translation>
    </message>
    <message>
      <source>Tamper Alert: Covered</source>
      <translation>Tamper 警告覆盖</translation>
    </message>
    <message>
      <source>Tamper Alert: Defocus</source>
      <translation>>Tamper 警告转移</translation>
    </message>
    <message>
      <source>Tamper Alert: Flashlight</source>
      <translation>警告：闪光灯</translation>
    </message>
    <message>
      <source>Tamper Alert: Shift</source>
      <translation>>Tamper 警告切换</translation>
    </message>
    <message>
      <source>VORON event</source>
      <translation>VORON 事件</translation>
    </message>
    <message>
      <source>Walk Detected</source>
      <translation>检测到移动</translation>
    </message>
    <message>
      <source>Warning: Thermal Signal</source>
      <translation>注意：热源信号</translation>
    </message>

    <!-- FaceRecognizerLoc -->
    <message>
      <source>Alarm</source>
      <translation>报警</translation>
    </message>
    <message>
      <source>Channel</source>
      <translation>通道</translation>
    </message>
    <message>
      <source>Face recognized</source>
      <translation>人脸识别</translation>
    </message>
    <message>
      <source>Folder</source>
      <translation>文件夹</translation>
    </message>
    <message>
      <source>Percentage of similarity</source>
      <translation>相似度比例</translation>
    </message>
    <message>
      <source>Unrecognized person</source>
      <translation>未识别人员</translation>
    </message>

    <!-- GateLoc -->
    <!-- Translated in 'FaceRecognizerLoc' block
    <message>
      <source>Channel</source>
      <translation>通道</translation>
    </message>
    -->
    <message>
      <source>Pacs GATE event</source>
      <translation> GATE 门禁事件</translation>
    </message>

    <!-- GpioLoc -->
    <message>
      <source>Associated channel</source>
      <translation>关联的通道</translation>
    </message>
    <message>
      <source>Input name</source>
      <translation>输入名称</translation>
    </message>

    <!-- Main -->
    <message>
      <source>""" Alarm types """</source>
      <translation>""" 报警类型 """</translation>
    </message>
    <message>
      <source>""" Aruco settings """</source>
      <translation>""" Aruco 设置 """</translation>
    </message>
    <message>
      <source>""" E-mail settings """</source>
      <translation>""" E-mail 设置 """</translation>
    </message>
    <message>
      <source>""" FTP settings """</source>
      <translation>""" FTP 设置 """</translation>
    </message>
    <message>
      <source>""" Face recognizer """</source>
      <translation>"""人脸识别 """</translation>
    </message>
    <message>
      <source>""" GATE settings """</source>
      <translation>""" GATE 设置 """</translation>
    </message>
    <message>
      <source>""" Neuro detector settings """</source>
      <translation>""" 神经网络检测设置 """</translation>
    </message>
    <message>
      <source>""" Operations with PACS """</source>
      <translation>"""  PACS操作设置 """</translation>
    </message>
    <message>
      <source>""" Operations with alarm inputs """</source>
      <translation>""" 报警输入操作 """</translation>
    </message>
    <message>
      <source>""" Operations with alarm outputs """</source>
      <translation>""" 报警输出操作"""</translation>
    </message>
    <message>
      <source>""" Optional settings """</source>
      <translation>""" 可选设置 """</translation>
    </message>
    <message>
      <source>""" Orion alarm """</source>
      <translation>""" Orion 报警"""</translation>
    </message>
    <message>
      <source>""" Reactions for events """</source>
      <translation>""" 事件响应 """</translation>
    </message>
    <message>
      <source>""" SIMT / Neurodetector settings """</source>
      <translation>""" SIMT / Neuro detector 设置 """</translation>
    </message>
    <message>
      <source>""" SMS settings """</source>
      <translation>""" SMS 设置"""</translation>
    </message>
    <message>
      <source>""" Settings BOPOH """</source>
      <translation>""" BOPOH 设置 """</translation>
    </message>
    <message>
      <source>""" Sigur settings """</source>
      <translation>""" Sigur 设置 """</translation>
    </message>
    <message>
      <source>"""Alarm monitor"""</source>
      <translation>"""Alarm monitor"""</translation>
    </message>
    <message>
      <source>1.close</source>
      <translation>1.关</translation>
    </message>
    <message>
      <source>2.open</source>
      <translation>2.开</translation>
    </message>
    <message>
      <source>3.close-open</source>
      <translation>3.关-开</translation>
    </message>
    <message>
      <source>4.open-close</source>
      <translation>4.开-关</translation>
    </message>
    <message>
      <source>5.close-close</source>
      <translation>5.关-关</translation>
    </message>
    <message>
      <source>6.open-open</source>
      <translation>6.开-开</translation>
    </message>
    <message>
      <source>A -> B</source>
      <translation>A -> B</translation>
    </message>
    <message>
      <source>A -> B,B -> A,any</source>
      <translation>A -> B,B -> A,any</translation>
    </message>
    <message>
      <source>Activation by</source>
      <translation>通过激活</translation>
    </message>
    <!-- Translated in 'FaceRecognizerLoc' block
    <message>
      <source>Alarm</source>
      <translation>报警</translation>
    </message>
    -->
    <message>
      <source>Alarm Monitor base settings</source>
      <translation>基本设置</translation>
    </message>
    <message>
      <source>Alarm Monitor optional settings</source>
      <translation>可选设置</translation>
    </message>
    <message>
      <source>Alarm channels displaying at once limit</source>
      <translation>单次显示报警通道数限制</translation>
    </message>
    <message>
      <source>Alarm group name</source>
      <translation>报警组名称</translation>
    </message>
    <message>
      <source>Alarm input for activation of operations</source>
      <translation>激活响应的报警输入</translation>
    </message>
    <message>
      <source>Alarm input for running the script (optional)</source>
      <translation>启动脚本的报警输入</translation>
    </message>
    <message>
      <source>Alarm input not found: %s</source>
      <translation>未检测到报警输入: %s</translation>
    </message>
    <message>
      <source>Alarm outputs</source>
      <translation>报警输出</translation>
    </message>
    <message>
      <source>Alarm person name</source>
      <translation>报警人员名称</translation>
    </message>
    <message>
      <source>Alarm reset if another template choosing by user</source>
      <translation>用户选择其他模板时重置报警</translation>
    </message>
    <message>
      <source>Alarm reset if no motion</source>
      <translation>无运动检测时重置报警</translation>
    </message>
    <message>
      <source>Alarm template</source>
      <translation>报警模板</translation>
    </message>
    <message>
      <source>AlarmMonitor</source>
      <translation>AlarmMonitor</translation>
    </message>
    <message>
      <source>Any person</source>
      <translation>所有人员</translation>
    </message>
    <message>
      <source>Aruco appeared</source>
      <translation>检测到Aruco码</translation>
    </message>
    <message>
      <source>Aruco codes</source>
      <translation>Aruco 码</translation>
    </message>
    <message>
      <source>Aruco disappeared</source>
      <translation>未检测到 Aruco 码</translation>
    </message>
    <message>
      <source>Aruco ignoring codes</source>
      <translation>Aruco忽略代码</translation>
    </message>
    <message>
      <source>Associated channel(s)</source>
      <translation>关联通道</translation>
    </message>
    <message>
      <source>At least one event type for GATE access control system must be selected</source>
      <translation>至少应为GATE门禁系统选择一种事件类型</translation>
    </message>
    <message>
      <source>Auto universal events</source>
      <translation>Auto universal 车辆事件</translation>
    </message>
    <message>
      <source>Basic template (after alarm)</source>
      <translation>基础模板（事件后）</translation>
    </message>
    <!-- Translated in 'EventsLoc' block
    <message>
      <source>Border Crossed A -> B</source>
      <translation>越界 A -> B</translation>
    </message>
    -->
    <!-- Translated in 'EventsLoc' block
    <message>
      <source>Border Crossed B -> A</source>
      <translation>越界 B -> A</translation>
    </message>
    -->
    <message>
      <source>Borders for reaction</source>
      <translation>需响应的报警划线</translation>
    </message>
    <message>
      <source>Buffering time before saving a shot (sec)</source>
      <translation>保存截图前缓存时间(s)</translation>
    </message>
    <message>
      <source>Card authentication passed</source>
      <translation>读卡授权通过</translation>
    </message>
    <!-- Translated in 'FaceRecognizerLoc' block
    <message>
      <source>Channel</source>
      <translation>通道</translation>
    </message>
    -->
    <message>
      <source>Choose alarm channels template!</source>
      <translation>请选择报警通道模板!</translation>
    </message>
    <message>
      <source>Choose output</source>
      <translation>选择输出</translation>
    </message>
    <message>
      <source>Continuous presence in zones alarm (*simt)</source>
      <translation>区域内持续出现的报警 (*simt)</translation>
    </message>
    <message>
      <source>Crossing border alarm (*simt)</source>
      <translation>越界报警 (*simt)</translation>
    </message>
    <message>
      <source>Crossing border direction (*simt)</source>
      <translation>越界方向 (*simt)</translation>
    </message>
    <message>
      <source>Crossing of line detection alarm (SMART event from camera)</source>
      <translation>越界检测报警 (SMART 智能相机)</translation>
    </message>
    <message>
      <source>Custom sound path (.wav)</source>
      <translation>定制声音路径 (.wav)</translation>
    </message>
    <message>
      <source>Delay before next operation with alarm otput(sec)</source>
      <translation>下次报警响应前的延迟(s)</translation>
    </message>
    <message>
      <source>Delay the start of the script</source>
      <translation>延迟运行脚本</translation>
    </message>
    <message>
      <source>Detector confidence coefficient (1-100 percent)</source>
      <translation>检测器置信系数 (1-100 %)</translation>
    </message>
    <message>
      <source>Display number for alarm template 1</source>
      <translation>报警模板1的显示编号</translation>
    </message>
    <message>
      <source>Display number for alarm template 2</source>
      <translation>报警模板2的显示编号</translation>
    </message>
    <message>
      <source>Display number for alarm template 3</source>
      <translation>报警模板3的显示编号</translation>
    </message>
    <message>
      <source>Display number to show pop-up</source>
      <translation>报警弹窗的显示编号</translation>
    </message>
    <message>
      <source>Distance violation</source>
      <translation>违规社交距离</translation>
    </message>
    <message>
      <source>Door open / close state duration, (sec)</source>
      <translation>开 / 关门时间 (s)</translation>
    </message>
    <message>
      <source>E-mail account, created in Trassir</source>
      <translation>Trassir E-mail 账号</translation>
    </message>
    <message>
      <source>Enable logging</source>
      <translation>可登录</translation>
    </message>
    <message>
      <source>Entrance in zones alarm (*simt, neuro)</source>
      <translation>进入区域报警 (*simt, neuro)</translation>
    </message>
    <message>
      <source>Escaping from zones alarm (*simt, neuro)</source>
      <translation>离开区域报警 (*simt, neuro)</translation>
    </message>
    <message>
      <source>Event subtype 'Controller: %1'</source>
      <translation>控制器事件子类: %1'</translation>
    </message>
    <message>
      <source>FTP folder on server</source>
      <translation>服务器FTP 文件夹</translation>
    </message>
    <message>
      <source>FTP host</source>
      <translation>FTP 主机</translation>
    </message>
    <message>
      <source>FTP passive mode</source>
      <translation>FTP 被动模式</translation>
    </message>
    <message>
      <source>FTP password</source>
      <translation>FTP 密码</translation>
    </message>
    <message>
      <source>FTP port</source>
      <translation>FTP 端口</translation>
    </message>
    <message>
      <source>FTP user</source>
      <translation>FTP 用户名</translation>
    </message>
    <message>
      <source>Face detection alarm</source>
      <translation>人脸检测报警</translation>
    </message>
    <message>
      <source>Face recognition alarm</source>
      <translation>人脸识别报警</translation>
    </message>
    <message>
      <source>Fire or smoke appears</source>
      <translation>检测到烟火</translation>
    </message>
    <message>
      <source>Fire or smoke went out</source>
      <translation>烟火停止</translation>
    </message>
    <message>
      <source>Folder name for saving shots</source>
      <translation>截图文件夹</translation>
    </message>
    <message>
      <source>Gate PACS events</source>
      <translation>Gate 事件</translation>
    </message>
    <message>
      <source>Group</source>
      <translation>组</translation>
    </message>
    <message>
      <source>Group not found: %s</source>
      <translation>[cn]Group not found: %s</translation>
    </message>
    <message>
      <source>Hotkey for manual activation of operations</source>
      <translation>手动激活响应快捷键</translation>
    </message>
    <message>
      <source>Ignore same events by period (sec)</source>
      <translation>时段内忽略同类事件 (s)</translation>
    </message>
    <message>
      <source>Ignore same events in period (sec)</source>
      <translation>时段内忽略同类事件 (s) (*neuro)</translation>
    </message>
    <message>
      <source>Ignoring identical events for a period, (sec)</source>
      <translation>时段内忽略相同事件 (sec)</translation>
    </message>
    <!-- Translated in 'EventsLoc' block
    <message>
      <source>Input Operations</source>
      <translation>输入响应</translation>
    </message>
    -->
    <message>
      <source>Input high to low alarm</source>
      <translation>从高到低输入报警</translation>
    </message>
    <message>
      <source>Input low to high alarm</source>
      <translation>从低到高输入报警</translation>
    </message>
    <message>
      <source>Input state to make reaction</source>
      <translation>进行联动的输入状态</translation>
    </message>
    <!-- Translated in 'EventsLoc' block
    <message>
      <source>Intrusion Detected</source>
      <translation>检测到入侵</translation>
    </message>
    -->
    <message>
      <source>Intrusion detection alarm (SMART event from camera)</source>
      <translation>入侵检测报警 (SMART相机)</translation>
    </message>
    <message>
      <source>Item abandoned alarm</source>
      <translation>物体遗留报警</translation>
    </message>
    <message>
      <source>Key found</source>
      <translation>找到钥匙</translation>
    </message>
    <message>
      <source>Mail recipient list separated by comma</source>
      <translation>邮件收件人列表，以逗号分隔</translation>
    </message>
    <message>
      <source>Make operations with PACS</source>
      <translation>PACS门禁操作</translation>
    </message>
    <message>
      <source>Make operations with outputs</source>
      <translation>输出操作</translation>
    </message>
    <message>
      <source>Make reactions for all events</source>
      <translation>对所有事件进行响应</translation>
    </message>
    <message>
      <source>Make reactions for event</source>
      <translation>对事件响应</translation>
    </message>
    <!-- Translated in 'EventsLoc' block
    <message>
      <source>Max count vehicles</source>
      <translation>车辆数量超限</translation>
    </message>
    -->
    <message>
      <source>Minimal compliance percentage in recognition</source>
      <translation>最小认可度百分比</translation>
    </message>
    <message>
      <source>Motion detection alarm</source>
      <translation>移动侦测报警</translation>
    </message>
    <message>
      <source>Multiple servers with the same name were found: %s</source>
      <translation>多台服务器重名: %s</translation>
    </message>
    <message>
      <source>Neuro border crossing</source>
      <translation>神经检测模块越界</translation>
    </message>
    <message>
      <source>Number of bicycle for alarm</source>
      <translation>非机动车报警数量</translation>
    </message>
    <message>
      <source>Number of people for alarm</source>
      <translation>人员报警数量</translation>
    </message>
    <message>
      <source>Number of vehicle for alarm</source>
      <translation>车辆报警数量</translation>
    </message>
    <message>
      <source>Numbers to send SMS messages(79999999999)</source>
      <translation>SMS短信数量(79999999999)</translation>
    </message>
    <message>
      <source>Object size alarm (*simt)</source>
      <translation>对象尺寸报警 (*simt)</translation>
    </message>
    <message>
      <source>Object speed alarm (*simt)</source>
      <translation>对象速度报警 (*simt)</translation>
    </message>
    <message>
      <source>Object track length alarm (*simt)</source>
      <translation>对象轨迹长度报警 (*simt)</translation>
    </message>
    <message>
      <source>Online shot</source>
      <translation>在线截图</translation>
    </message>
    <message>
      <source>Only one screenshot per period (sec)</source>
      <translation>每张截图对应周期 (sec)</translation>
    </message>
    <message>
      <source>Only sensors alarm</source>
      <translation>探测器报警</translation>
    </message>
    <message>
      <source>Operation type</source>
      <translation>响应类型</translation>
    </message>
    <message>
      <source>Orion disabled</source>
      <translation>Orion 被禁止</translation>
    </message>
    <message>
      <source>Orion events alarm</source>
      <translation>Orion 事件报警</translation>
    </message>
    <message>
      <source>Other</source>
      <translation>其他</translation>
    </message>
    <message>
      <source>PACS name</source>
      <translation>PACS 门禁名称</translation>
    </message>
    <message>
      <source>PACS type</source>
      <translation>PACS 门禁类型</translation>
    </message>
    <message>
      <source>Pass happened</source>
      <translation>通过事件</translation>
    </message>
    <message>
      <source>Password or MD-5 hash in lowercase</source>
      <translation>密码或 MD-5 小写哈希</translation>
    </message>
    <message>
      <source>People detected (SMART event from camera)</source>
      <translation>人员检测 (SMART 摄像机事件)</translation>
    </message>
    <message>
      <source>Person</source>
      <translation>人员</translation>
    </message>
    <message>
      <source>Person with fever</source>
      <translation>高温人群</translation>
    </message>
    <message>
      <source>Person without a mask</source>
      <translation>人员未佩戴口罩</translation>
    </message>
    <message>
      <source>Person without helmet</source>
      <translation>人员未佩戴安全帽</translation>
    </message>
    <message>
      <source>Person without uniform</source>
      <translation> 人员未穿工装</translation>
    </message>
    <message>
      <source>Playback in archive</source>
      <translation>录像中回放</translation>
    </message>
    <message>
      <source>Popup duration</source>
      <translation>弹出时间</translation>
    </message>
    <message>
      <source>React for bicycles</source>
      <translation>非机动车响应</translation>
    </message>
    <message>
      <source>React for people</source>
      <translation>人员响应</translation>
    </message>
    <message>
      <source>React for vehicle</source>
      <translation>车辆响应</translation>
    </message>
    <message>
      <source>Reactions on objects presence in neuro zones</source>
      <translation>在神经网络区域检测对象</translation>
    </message>
    <message>
      <source>SIMT detector alarm</source>
      <translation>SIMT 探测器报警</translation>
    </message>
    <message>
      <source>SIP code</source>
      <translation>SIP 码</translation>
    </message>
    <message>
      <source>SIP number</source>
      <translation>SIP 序号</translation>
    </message>
    <message>
      <source>SMS service login</source>
      <translation>SMS 服务登录</translation>
    </message>
    <message>
      <source>Sabotage alarm</source>
      <translation>防破坏报警</translation>
    </message>
    <message>
      <source>Save screenshot in screenshot folder</source>
      <translation>将截屏存入Screeshot目录</translation>
    </message>
    <message>
      <source>Schedule for running the script</source>
      <translation>允许脚本计划时间</translation>
    </message>
    <message>
      <source>Screenshot of the sub-stream (experimental)</source>
      <translation>辅码流截图 (实验)</translation>
    </message>
    <message>
      <source>Select PACS name</source>
      <translation>选择 PACS名称</translation>
    </message>
    <message>
      <source>Select a server with persons db (Face recognizer section)</source>
      <translation>选择人脸数据库服务器（人脸部分）</translation>
    </message>
    <message>
      <source>Selected template not found %s</source>
      <translation>所选模板丢失: %s</translation>
    </message>
    <message>
      <source>Send SMS notification</source>
      <translation>发送短信提示</translation>
    </message>
    <message>
      <source>Send cloud alarm by token</source>
      <translation>按照令牌发送云报警</translation>
    </message>
    <message>
      <source>Send code to SIP (server only)</source>
      <translation>发送代码至SIP</translation>
    </message>
    <message>
      <source>Send notification to e-mail</source>
      <translation>发送电子邮件提示</translation>
    </message>
    <message>
      <source>Send screen to FTP</source>
      <translation>发送屏幕状态至FTP</translation>
    </message>
    <message>
      <source>Send screen to Telegram (only on server)</source>
      <translation>发送屏幕状态至Telegram (服务器端)</translation>
    </message>
    <message>
      <source>Send screen to e-mail</source>
      <translation>发送屏幕状态至电子邮件</translation>
    </message>
    <message>
      <source>Server with name %s could not be found</source>
      <translation>服务器中断连接: %s </translation>
    </message>
    <message>
      <source>Server with the necessary folders of persons database</source>
      <translation>人员库服务器</translation>
    </message>
    <message>
      <source>Shot storage time (days)</source>
      <translation>截图保存时间（天）</translation>
    </message>
    <message>
      <source>Shot time correction ('-' - before, '+' - after)(ms)</source>
      <translation>截图时间校对 ('-' - 前, '+' - 后)(ms)</translation>
    </message>
    <message>
      <source>Shots with figures</source>
      <translation>带有检测框截图</translation>
    </message>
    <message>
      <source>Show channel</source>
      <translation>显示通道</translation>
    </message>
    <message>
      <source>Show channel with alarm</source>
      <translation>显示报警通道</translation>
    </message>
    <message>
      <source>Show channel,Playback in archive</source>
      <translation>显示通道，在录像中回放</translation>
    </message>
    <message>
      <source>Show pop-up</source>
      <translation>显示弹窗</translation>
    </message>
    <message>
      <source>Show text message</source>
      <translation>显示信息文本</translation>
    </message>
    <message>
      <source>Sigur events alarm</source>
      <translation>Sigur 事件报警</translation>
    </message>
    <message>
      <source>Sound detection alarm</source>
      <translation>噪声检测报警</translation>
    </message>
    <message>
      <source>Sound file name</source>
      <translation>噪声文件名</translation>
    </message>
    <message>
      <source>Sound notification</source>
      <translation>噪声提示</translation>
    </message>
    <message>
      <source>Specified E-mail account not found</source>
      <translation>无法找到电子邮件账户</translation>
    </message>
    <message>
      <source>Specify alarm group name</source>
      <translation>找不到组名称</translation>
    </message>
    <message>
      <source>Specify aruco codes</source>
      <translation>指定Aruco 码</translation>
    </message>
    <message>
      <source>Specify borders in section 'Borders' for reactions</source>
      <translation>划定需要响应的边界</translation>
    </message>
    <message>
      <source>Specify person name</source>
      <translation>指定人员名称</translation>
    </message>
    <message>
      <source>Specify recipient(s) e-mail(s) separated by comma</source>
      <translation>指定电子邮件收件人（逗号分隔）</translation>
    </message>
    <message>
      <source>Specify zones names</source>
      <translation>指定区域名称</translation>
    </message>
    <message>
      <source>Successful detections, % (*long-lasting)</source>
      <translation>检测到目标, % (*持续)</translation>
    </message>
    <message>
      <source>Text message showing duration(sec)</source>
      <translation>持续显示信息时间（s）</translation>
    </message>
    <message>
      <source>The SIP code can only be sent on the server</source>
      <translation>SIP码由服务器发送</translation>
    </message>
    <message>
      <source>The appearance of an object in the neuro zone</source>
      <translation>Neuro区域出现检测目标</translation>
    </message>
    <message>
      <source>The controller is disabled</source>
      <translation>控制器被禁用</translation>
    </message>
    <message>
      <source>The controller is enabled</source>
      <translation>控制器开启</translation>
    </message>
    <message>
      <source>The display duration of the channel in alarm template (sec)</source>
      <translation>报警通道在模板的显示时间</translation>
    </message>
    <message>
      <source>The time of the open / closed state of the door must be in the range [1, 3600] sec</source>
      <translation>门开关状态的时间范围 [1, 3600] 秒</translation>
    </message>
    <message>
      <source>The type of work for detection in zone</source>
      <translation>区域内检测的工作类型</translation>
    </message>
    <message>
      <source>The type of work should be '%s' or '%s'</source>
      <translation>工作类型应该是 '%s' or '%s'</translation>
    </message>
    <message>
      <source>There can only be one server with a database of persons</source>
      <translation>人员数据库应在同一台服务器内</translation>
    </message>
    <message>
      <source>Time of observation before the alarm (*long-lasting), sec</source>
      <translation>报警前延迟时间 (*持续), 秒</translation>
    </message>
    <message>
      <source>Time, spent by object in zone, before alarm(sec)</source>
      <translation>报警前目标在区域中停留时间（s）</translation>
    </message>
    <!-- Translated in 'FaceRecognizerLoc' block
    <message>
      <source>Unrecognized person</source>
      <translation>未识别人员</translation>
    </message>
    -->
    <message>
      <source>User Telegram id</source>
      <translation>用户Telegram id</translation>
    </message>
    <message>
      <source>Voron events</source>
      <translation>Voron 事件</translation>
    </message>
    <message>
      <source>Working channels</source>
      <translation>有效通道</translation>
    </message>
    <message>
      <source>Working servers</source>
      <translation>服务器运行中</translation>
    </message>
    <message>
      <source>You must specify channels with face recognition in the Working channels field</source>
      <translation>应在工作频道字段中指定具有面部识别功能的频道</translation>
    </message>
    <message>
      <source>You must specify the SIP code</source>
      <translation>应指定SIP 码</translation>
    </message>
    <message>
      <source>You must specify the SIP number</source>
      <translation>应指定SIP 编号</translation>
    </message>
    <message>
      <source>You must specify the server (s) from which the channels are used</source>
      <translation>应指定工作频道所属的服务器</translation>
    </message>
    <message>
      <source>Zone names to check (for events in zone)</source>
      <translation>区域名称 (*simt)</translation>
    </message>
    <message>
      <source>Zones names for detections (for all channels)</source>
      <translation>检测区域名称（所有通道）</translation>
    </message>
    <message>
      <source>alert in a zone</source>
      <translation>区域告警</translation>
    </message>
    <message>
      <source>automatic alarm confirmation</source>
      <translation>自动报警确认</translation>
    </message>
    <message>
      <source>close thе door</source>
      <translation>关门</translation>
    </message>
    <message>
      <source>closed</source>
      <translation>关闭</translation>
    </message>
    <message>
      <source>immediate</source>
      <translation>立即</translation>
    </message>
    <message>
      <source>long-lasting</source>
      <translation>更长的观察</translation>
    </message>
    <message>
      <source>manual alarm confirmation</source>
      <translation>手动报警确认</translation>
    </message>
    <message>
      <source>no</source>
      <translation>否</translation>
    </message>
    <message>
      <source>open the door</source>
      <translation>开门</translation>
    </message>
    <message>
      <source>opened</source>
      <translation>打开</translation>
    </message>
    <message>
      <source>the zone is unguarded</source>
      <translation>区域未设防</translation>
    </message>
    <message>
      <source>zone failure</source>
      <translation>区域失效</translation>
    </message>
    <message>
      <source>zone guarded</source>
      <translation>区域设防</translation>
    </message>

    <!-- NeuroLoc -->
    <message>
      <source>Bicycle</source>
      <translation>非机动车</translation>
    </message>
    <message>
      <source>Border</source>
      <translation>边界</translation>
    </message>
    <message>
      <source>Event time</source>
      <translation>事件时间</translation>
    </message>
    <message>
      <source>Last detection quantity</source>
      <translation>上次检测的数量</translation>
    </message>
    <message>
      <source>Level to react</source>
      <translation>响应级别</translation>
    </message>
    <!-- Translated in 'Main' block
    <message>
      <source>Person</source>
      <translation>人员</translation>
    </message>
    -->
    <message>
      <source>Vehicle</source>
      <translation>车辆</translation>
    </message>
    <message>
      <source>Zone name</source>
      <translation>区域名称</translation>
    </message>

    <!-- PopupLoc -->
    <message>
      <source>Cancel</source>
      <translation>取消</translation>
    </message>
    <message>
      <source>Show event in archive</source>
      <translation>在录像中显示事件</translation>
    </message>

    <!-- SimtLoc -->
    <!-- Translated in 'GpioLoc' block
    <message>
      <source>Associated channel</source>
      <translation>关联的通道</translation>
    </message>
    -->
    <message>
      <source>Border name</source>
      <translation>区域名称</translation>
    </message>
    <!-- Translated in 'NeuroLoc' block
    <message>
      <source>Zone name</source>
      <translation>区域名称</translation>
    </message>
    -->
    <message>
      <source>any</source>
      <translation>所有</translation>
    </message>
    <message>
      <source>Action type</source>
      <translation>动作类型</translation>
    </message>

    <!-- Not used in current script -->
    <message>
      <source>1.close,2.open,3.close-open,4.open-close,5.close-close,6.open-open</source>
      <translation>1.关,2.开,3.关-开,4.开-关,5.关-关,6.开-开</translation>
    </message>
    <message>
      <source>Alarm input not found: {}</source>
      <translation>未检测到报警输入: {}</translation>
    </message>
    <message>
      <source>Alert: Flashlight</source>
      <translation>警告：闪光灯</translation>
    </message>
    <message>
      <source>Continuous presence detection zones (*simt)</source>
      <translation>检测区域内持续出现 (*simt)</translation>
    </message>
    <message>
      <source>Controller alarm: %1</source>
      <translation>控制器报警: %1</translation>
    </message>
    <message>
      <source>Door open / close time, (s)</source>
      <translation>开 / 关门时间 (s)</translation>
    </message>
    <message>
      <source>Ignore same events by period(sec) (*neuro)</source>
      <translation>时段内忽略同类事件(s) (*neuro)</translation>
    </message>
    <message>
      <source>Key found,Pass happened,any</source>
      <translation>找到钥匙并通行</translation>
    </message>
    <message>
      <source>Multiple servers with the same name were found: {}</source>
      <translation>多台服务器重名: {}</translation>
    </message>
    <message>
      <source>No,Card authentication passed,The controller is disabled,The controller is enabled,Controller is connected,Controller: %1,Invalid card: %1,Controller alarm: %1</source>
      <translation>否 卡片授权通过，控制器禁止，控制器开启，控制器连接，控制器: %1,非法卡: %1,控制器报警: %1</translation>
    </message>
    <message>
      <source>No,Deny: %1 (%2),Allow: %1 (%2),Pass: %1 (%2),Access Point Disconnected,Access Point Connected,Access Point Once Opened,Access Point: %1,Alarm: %1(%2),Access Point Closed To All,Access Point Opened To All,Access Point Allows By Key</source>
      <translation>拒绝: %1 (%2),允许: %1 (%2),通过: %1 (%2),进出点断开,进出点连接，进出点曾打开，进出点: %1,Alarm: %1(%2),进出点关闭，进出点打开，进出点钥匙进入</translation>
    </message>
    <message>
      <source>No,Intrusion Alert,Fire Detected,Allowed Access By Key,Allowed Access By Key,Door Restored,Door Broken,Door Blocked,No Access To All,No Access %1,Access Granted %1,No Access %1,Reader Contact Lost,Walk Detected,Free Walk Allowed,Armed,Orion disabled</source>
      <translation>否，入侵警告，检测到火灾，可用钥匙进入，可用钥匙进入，门被重置，门被破坏，门被阻止，所有人无法访问，没有访问权限％1，已授予访问权限％1，没有访问权限％1，读卡器断开 ，行走检测，允许行走，布防，Orion 禁用</translation>
    </message>
    <message>
      <source>No,alert in a zone,zone failure,the zone is unguarded,zone guarded,manual alarm confirmation,automatic alarm confirmation</source>
      <translation>否，区域警报，区域故障，区域未设防，区域已设防，手动警报确认，自动警报确认</translation>
    </message>
    <message>
      <source>Person,Group,Any person,Unrecognized person</source>
      <translation>人员，组，所有人，未识别组</translation>
    </message>
    <message>
      <source>Quantity</source>
      <translation>质量</translation>
    </message>
    <message>
      <source>Selected template not found {}</source>
      <translation>所选模板丢失 {}</translation>
    </message>
    <message>
      <source>Server with name {} could not be found</source>
      <translation>{} 服务器中断连接</translation>
    </message>
    <message>
      <source>The type of work should be '{}' or '{}'</source>
      <translation>工作类型应为 '{}' 或 '{}'</translation>
    </message>
    <message>
      <source>close</source>
      <translation>关</translation>
    </message>
    <message>
      <source>close-close</source>
      <translation>关-关</translation>
    </message>
    <message>
      <source>close-open</source>
      <translation>关-开</translation>
    </message>
    <message>
      <source>open</source>
      <translation>开</translation>
    </message>
    <message>
      <source>open the door,close the door</source>
      <translation>开门，关门</translation>
    </message>
    <message>
      <source>open-close</source>
      <translation>开-关</translation>
    </message>
    <message>
      <source>open-open</source>
      <translation>开-开</translation>
    </message>

    <message>
      <source>Suspicious pose</source>
      <translation>可疑姿势</translation>
    </message>

  </context>
</TS>