<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<!-- Automatically generated by ts_generator v1.0.0 at 2020-12-11 -->
<TS version="2.1" language="ru" sourcelanguage="en">
  <context>
    <name>AlarmMonitor</name>

    <!-- EventsLoc -->
    <message>
      <source>Access Denied %1</source>
      <translation>Доступ запрещен %1</translation>
    </message>
    <message>
      <source>Access Granted %1</source>
      <translation>Доступ предоставлен %1</translation>
    </message>
    <message>
      <source>Access Point Allows By Key</source>
      <translation>Доступ доступен по ключу</translation>
    </message>
    <message>
      <source>Access Point Closed To All</source>
      <translation>Дверь заблокирована</translation>
    </message>
    <message>
      <source>Access Point Connected</source>
      <translation>Точка доступа. Соединение установлено</translation>
    </message>
    <message>
      <source>Access Point Disconnected</source>
      <translation>Точка доступа. Соединение разорвано</translation>
    </message>
    <message>
      <source>Access Point Once Opened</source>
      <translation>Точка доступа открыта на один проход</translation>
    </message>
    <message>
      <source>Access Point Opened To All</source>
      <translation>Установлен режим работы 'открыто'</translation>
    </message>
    <message>
      <source>Access Point: %1</source>
      <translation>Точка Доступа: %1</translation>
    </message>
    <message>
      <source>Alarm: %1 (%2)</source>
      <translation>Тревога: %1 (%2)</translation>
    </message>
    <message>
      <source>Allow: %1 (%2)</source>
      <translation>Доступ предоставлен: %1(%2)</translation>
    </message>
    <message>
      <source>Allowed Access By Key</source>
      <translation>Доступен доступ по ключу</translation>
    </message>
    <message>
      <source>Armed</source>
      <translation>Взят на охрану</translation>
    </message>
    <message>
      <source>Aruco entered the zone</source>
      <translation>Появление аруко в зоне</translation>
    </message>
    <message>
      <source>Aruco left the zone</source>
      <translation>Аруко код покинул зону</translation>
    </message>
    <message>
      <source>Border Crossed A -> B</source>
      <translation>Пересечение границы в направлении A -> B</translation>
    </message>
    <message>
      <source>Border Crossed B -> A</source>
      <translation>Пересечение границы в направлении B -> A</translation>
    </message>
    <message>
      <source>Controller Alarm: %1</source>
      <translation>Тревога контроллера: %1</translation>
    </message>
    <message>
      <source>Controller Connected</source>
      <translation>Контроллер подключен</translation>
    </message>
    <message>
      <source>Controller Disconnected</source>
      <translation>Контроллер отключен</translation>
    </message>
    <message>
      <source>Controller: %1</source>
      <translation>Контроллер %1</translation>
    </message>
    <message>
      <source>CrossLine Detected</source>
      <translation>Пересечение границы</translation>
    </message>
    <message>
      <source>Deny: %1 (%2)</source>
      <translation>Доступ отклонен: %1(%2)</translation>
    </message>
    <message>
      <source>Door Blocked</source>
      <translation>Дверь заблокирована</translation>
    </message>
    <message>
      <source>Door Broken</source>
      <translation>Дверь взломана</translation>
    </message>
    <message>
      <source>Door Restored</source>
      <translation>Восстановлено состояние двери</translation>
    </message>
    <message>
      <source>FACS Connected</source>
      <translation>СКУД. Соединение установлено</translation>
    </message>
    <message>
      <source>FACS Disconnected</source>
      <translation>СКУД. Соединение разорвано</translation>
    </message>
    <message>
      <source>FACS: %1</source>
      <translation>СКУД:%1</translation>
    </message>
    <message>
      <source>Face Detected</source>
      <translation>Обнаружено лицо</translation>
    </message>
    <message>
      <source>Face Recognized</source>
      <translation>Распознано лицо</translation>
    </message>
    <message>
      <source>Fire</source>
      <translation>Обнаружен огонь</translation>
    </message>
    <message>
      <source>Fire Detected</source>
      <translation>Обнаружен огонь</translation>
    </message>
    <message>
      <source>Fire Stopped</source>
      <translation>Огонь потух</translation>
    </message>
    <message>
      <source>Free Walk Allowed</source>
      <translation>Свободный проход разрешен</translation>
    </message>
    <message>
      <source>Input High to Low</source>
      <translation>Размыкание входа</translation>
    </message>
    <message>
      <source>Input Low to High</source>
      <translation>Замыкание входа</translation>
    </message>
    <message>
      <source>Input Operations</source>
      <translation>Изменение состояния входа</translation>
    </message>
    <message>
      <source>Intrusion Alert</source>
      <translation>Тревога проникновения</translation>
    </message>
    <message>
      <source>Intrusion Detected</source>
      <translation>Вторжение в зону</translation>
    </message>
    <message>
      <source>Invalid card: %1</source>
      <translation>Недействительная карта %1</translation>
    </message>
    <message>
      <source>Item Abandoned</source>
      <translation>Обнаружен оставленный предмет</translation>
    </message>
    <message>
      <source>Item Missing</source>
      <translation>Оставленный предмет исчез</translation>
    </message>
    <message>
      <source>Left Object Detected</source>
      <translation>Обнаружен оставленный предмет</translation>
    </message>
    <message>
      <source>Legal card authentication passed: %1</source>
      <translation>Проверка подлинности карты пройдена: %1</translation>
    </message>
    <message>
      <source>Max count bicycles</source>
      <translation>Детектировано максимальное количество велосипедов</translation>
    </message>
    <message>
      <source>Max count people</source>
      <translation>Детектировано максимальное количество людей</translation>
    </message>
    <message>
      <source>Max count vehicles</source>
      <translation>Детектировано максимальное количество автомобилей</translation>
    </message>
    <message>
      <source>Motion Start</source>
      <translation>Движение обнаружено</translation>
    </message>

    <message>
      <source>Signal Lost</source>
      <translation>Сигнал потерян</translation>
    </message>
    <message>
      <source>Signal Restored</source>
      <translation>Сигнал восстановлен</translation>
    </message>


    <message>
      <source>No Access %1</source>
      <translation>Нет доступа %1</translation>
    </message>
    <message>
      <source>No Access To All</source>
      <translation>Доступ запрещен для всех</translation>
    </message>
    <message>
      <source>Object Entered the Zone</source>
      <translation>Объект вошел в зону</translation>
    </message>
    <message>
      <source>Object Left the Zone</source>
      <translation>Объект покинул зону</translation>
    </message>
    <message>
      <source>Object Size Alarm</source>
      <translation>Тревога по размеру объекта</translation>
    </message>
    <message>
      <source>Object Speed Alarm</source>
      <translation>Тревога по скорости объекта</translation>
    </message>
    <message>
      <source>Object Track Length Alarm</source>
      <translation>Тревога по длине трека объекта</translation>
    </message>
    <message>
      <source>Object presence alarm</source>
      <translation>Присутствие объекта в зоне</translation>
    </message>
    <message>
      <source>Orion Disconnected</source>
      <translation>Орион отключен</translation>
    </message>
    <message>
      <source>Pass: %1 (%2)</source>
      <translation>Проход:%1(%2)</translation>
    </message>
    <message>
      <source>People Detected</source>
      <translation>Обнаружены люди (событие с камеры)</translation>
    </message>
    <message>
      <source>Person without helmet detected</source>
      <translation>Обнаружен человек без каски</translation>
    </message>
    <message>
      <source>Person without mask found</source>
      <translation>Человек без маски</translation>
    </message>
    <message>
      <source>Person without uniform detected</source>
      <translation>Обнаружен человек без спецодежды</translation>
    </message>
    <message>
      <source>Plate detected</source>
      <translation>Распознан номер</translation>
    </message>
    <message>
      <source>Reader Contact Lost</source>
      <translation>Потеряно соединение со считывателем</translation>
    </message>
    <message>
      <source>Slow Down Detected</source>
      <translation>Обнаружен оставленный предмет</translation>
    </message>
    <message>
      <source>Smoke Detected</source>
      <translation>Обнаружен дым</translation>
    </message>
    <message>
      <source>Social distance violation detected</source>
      <translation>Нарушение социальной дистанции</translation>
    </message>
    <message>
      <source>Sound Detected</source>
      <translation>Обнаружен звук</translation>
    </message>
    <message>
      <source>Tamper Alert</source>
      <translation>Саботаж</translation>
    </message>
    <message>
      <source>Tamper Alert: Covered</source>
      <translation>Саботаж: закрытие</translation>
    </message>
    <message>
      <source>Tamper Alert: Defocus</source>
      <translation>Саботаж: дефокусировка</translation>
    </message>
    <message>
      <source>Tamper Alert: Flashlight</source>
      <translation>Саботаж: засветка</translation>
    </message>
    <message>
      <source>Tamper Alert: Shift</source>
      <translation>Саботаж: сдвиг</translation>
    </message>
    <message>
      <source>VORON event</source>
      <translation>Событие системы BOPOH</translation>
    </message>
    <message>
      <source>Walk Detected</source>
      <translation>Обнаружен проход</translation>
    </message>
    <message>
      <source>Warning: Thermal Signal</source>
      <translation>Внимание: превышение температуры</translation>
    </message>

    <!-- FaceRecognizerLoc -->
    <message>
      <source>Alarm</source>
      <translation>Тревога</translation>
    </message>
    <message>
      <source>Channel</source>
      <translation>Канал</translation>
    </message>
    <message>
      <source>Face recognized</source>
      <translation>Лицо распознано</translation>
    </message>
    <message>
      <source>Folder</source>
      <translation>Папка</translation>
    </message>
    <message>
      <source>Percentage of similarity</source>
      <translation>Процент соответствия</translation>
    </message>
    <message>
      <source>Unrecognized person</source>
      <translation>Неопознанное лицо</translation>
    </message>

    <!-- GateLoc -->
    <!-- Translated in 'FaceRecognizerLoc' block
    <message>
      <source>Channel</source>
      <translation>Канал</translation>
    </message>
    -->
    <message>
      <source>Pacs GATE event</source>
      <translation>события СКУД GATE</translation>
    </message>

    <!-- GpioLoc -->
    <message>
      <source>Associated channel</source>
      <translation>Ассоциированный канал</translation>
    </message>
    <message>
      <source>Input name</source>
      <translation>Имя тревожного входа</translation>
    </message>

    <!-- Main -->
    <message>
      <source>""" Alarm types """</source>
      <translation>""" Типы тревоги """</translation>
    </message>
    <message>
      <source>""" Aruco settings """</source>
      <translation>""" Настройки детектора аруко """</translation>
    </message>
    <message>
      <source>""" E-mail settings """</source>
      <translation>""" Настройки e-mail """</translation>
    </message>
    <message>
      <source>""" FTP settings """</source>
      <translation>""" Настройи ftp"""</translation>
    </message>
    <message>
      <source>""" Face recognizer """</source>
      <translation>""" Распознаватель лиц """</translation>
    </message>
    <message>
      <source>""" GATE settings """</source>
      <translation>""" Настройки GATE """</translation>
    </message>
    <message>
      <source>""" Neuro detector settings """</source>
      <translation>""" Настройки нейронного детектора """</translation>
    </message>
    <message>
      <source>""" Operations with PACS """</source>
      <translation>""" Операции со СКУД """</translation>
    </message>
    <message>
      <source>""" Operations with alarm inputs """</source>
      <translation>""" Операции с тревожными входами """</translation>
    </message>
    <message>
      <source>""" Operations with alarm outputs """</source>
      <translation>""" Операции с тревожными выходами """</translation>
    </message>
    <message>
      <source>""" Optional settings """</source>
      <translation>""" Дополнительно """</translation>
    </message>
    <message>
      <source>""" Orion alarm """</source>
      <translation>""" Тревога Orion """</translation>
    </message>
    <message>
      <source>""" Reactions for events """</source>
      <translation>""" Реакции по событиям """</translation>
    </message>
    <message>
      <source>""" SIMT / Neurodetector settings """</source>
      <translation>""" Настройки SIMT / нейродетектора """</translation>
    </message>
    <message>
      <source>""" SMS settings """</source>
      <translation>""" Настройки SMS """</translation>
    </message>
    <message>
      <source>""" Settings BOPOH """</source>
      <translation>""" Настройки BOPOH """</translation>
    </message>
    <message>
      <source>""" Sigur settings """</source>
      <translation>""" Настройки Sigur """</translation>
    </message>
    <message>
      <source>"""Alarm monitor"""</source>
      <translation>""" Тревожный монитор """</translation>
    </message>


    <message>
      <source>Action type</source>
      <translation>Тип действия</translation>
    </message>

    <message>
      <source>1.close</source>
      <translation>1.замкнуть</translation>
    </message>
    <message>
      <source>2.open</source>
      <translation>2.разомкнуть</translation>
    </message>
    <message>
      <source>3.close-open</source>
      <translation>3.замкнуть-разомкнуть</translation>
    </message>
    <message>
      <source>4.open-close</source>
      <translation>4.разомкнуть-замкнуть</translation>
    </message>
    <message>
      <source>5.close-close</source>
      <translation>5.замкнуть-замкнуть</translation>
    </message>
    <message>
      <source>6.open-open</source>
      <translation>6.разомкнуть-разомкнуть</translation>
    </message>
    <message>
      <source>A -> B</source>
      <translation>A -> B</translation>
    </message>
    <message>
      <source>A -> B,B -> A,any</source>
      <translation>A -> B,B -> A,любое</translation>
    </message>
    <message>
      <source>Activation by</source>
      <translation>Активация по</translation>
    </message>
    <message>
      <source>Add a video to the alarm content</source>
      <translation>Добавить видео при генерации тревог</translation>
    </message>
    <message>
      <source>Add an image to the alarm content</source>
      <translation>Добавить изображение при генерации тревог</translation>
    </message>

    <message>
      <source>Alarms can only be generated on servers</source>
      <translation>Тревоги могут генерироваться только на сервере</translation>
    </message>

    <!-- Translated in 'FaceRecognizerLoc' block
    <message>
      <source>Alarm</source>
      <translation>Тревога</translation>
    </message>
    -->
    <message>
      <source>Alarm Monitor base settings</source>
      <translation>Базовые настройки ТМ</translation>
    </message>
    <message>
      <source>Alarm Monitor optional settings</source>
      <translation>Опциональные настройки ТМ</translation>
    </message>
    <message>
      <source>Alarm channels displaying at once limit</source>
      <translation>Лимит одновременно отображаемых каналов</translation>
    </message>
    <message>
      <source>Alarm group name</source>
      <translation>Имя тревожной группы</translation>
    </message>
    <message>
      <source>Alarm input for activation of operations</source>
      <translation>Тревожный вход для активации операций</translation>
    </message>
    <message>
      <source>Alarm input for running the script (optional)</source>
      <translation>Тревожный вход для работы скрипта (дополнительно)</translation>
    </message>
    <message>
      <source>Alarm input not found: %s</source>
      <translation>Тревожный вход не найден: %s</translation>
    </message>
    <message>
      <source>Alarm outputs</source>
      <translation>Тревожные выходы</translation>
    </message>
    <message>
      <source>Alarm person name</source>
      <translation>Имя тревожной персоны</translation>
    </message>
    <message>
      <source>Alarm reset if another template choosing by user</source>
      <translation>Сброс треовги при смене шаблона</translation>
    </message>
    <message>
      <source>Alarm reset if no motion</source>
      <translation>Сброс тревоги при отсутствии движения на канале</translation>
    </message>
    <message>
      <source>Alarm template</source>
      <translation>Тревожный шаблон</translation>
    </message>
    <message>
      <source>AlarmMonitor</source>
      <translation>AlarmMonitor</translation>
    </message>
    <message>
      <source>Any person</source>
      <translation>Любое лицо</translation>
    </message>
    <message>
      <source>Aruco appeared</source>
      <translation>Обнаружение аруко кода</translation>
    </message>
    <message>
      <source>Aruco codes</source>
      <translation>Аруко коды</translation>
    </message>
    <message>
      <source>Aruco disappeared</source>
      <translation>Исчезновение аруко кода</translation>
    </message>
    <message>
      <source>Aruco ignoring codes</source>
      <translation>Игнорировать указанные коды</translation>
    </message>
    <message>
      <source>Associated channel(s)</source>
      <translation>Ассоциированные канал(ы)</translation>
    </message>
    <message>
      <source>At least one event type for GATE access control system must be selected</source>
      <translation>Хотя бы один тип событий для СКУД GATE должен быть выбран</translation>
    </message>
    <message>
      <source>Auto universal events</source>
      <translation>События AutoUniversal</translation>
    </message>
    <message>
      <source>Basic template (after alarm)</source>
      <translation>Базовый шаблон (по окон-ю тревоги)</translation>
    </message>
    <!-- Translated in 'EventsLoc' block
    <message>
      <source>Border Crossed A -> B</source>
      <translation>Пересечение границы в направлении A -> B</translation>
    </message>
    -->
    <!-- Translated in 'EventsLoc' block
    <message>
      <source>Border Crossed B -> A</source>
      <translation>Пересечение границы в направлении B -> A</translation>
    </message>
    -->
    <message>
      <source>Borders for reaction</source>
      <translation>Границы для реакции</translation>
    </message>
    <message>
      <source>Buffering time before saving a shot (sec)</source>
      <translation>Время буферизации перед сохранением шота, сек</translation>
    </message>
    <message>
      <source>Card authentication passed</source>
      <translation>Проверка подлинности карты пройдена</translation>
    </message>
    <!-- Translated in 'FaceRecognizerLoc' block
    <message>
      <source>Channel</source>
      <translation>Канал</translation>
    </message>
    -->
    <message>
      <source>Choose alarm channels template!</source>
      <translation>Тревожный шаблон не выбран!</translation>
    </message>
    <message>
      <source>Choose output</source>
      <translation>Выберите тревожный выход</translation>
    </message>
    <message>
      <source>Continuous presence in zones alarm (*simt)</source>
      <translation>Тревога при длительном прис-ии объекта в зоне (*simt)</translation>
    </message>
    <message>
      <source>Crossing border alarm (*simt)</source>
      <translation>Тревога при пересечении границы (*simt)</translation>
    </message>
    <message>
      <source>Crossing border direction (*simt)</source>
      <translation>Направление пересечения границы (*simt)</translation>
    </message>
    <message>
      <source>Crossing of line detection alarm (SMART event from camera)</source>
      <translation>Тревога при пересечении границы (SMART событие с камеры)</translation>
    </message>
    <message>
      <source>Custom sound path (.wav)</source>
      <translation>Путь к звуковому файлу(.wav)</translation>
    </message>
    <message>
      <source>Delay before next operation with alarm otput(sec)</source>
      <translation>Задержка перед последующей операцией с тревожным выходом (сек)</translation>
    </message>
    <message>
      <source>Delay the start of the script</source>
      <translation>Задержка старта скрипта(сек)</translation>
    </message>
    <message>
      <source>Detector confidence coefficient (1-100 percent)</source>
      <translation>Коэффициент уверенности детектора (1-100)</translation>
    </message>
    <message>
      <source>Display number for alarm template 1</source>
      <translation>Номер дисплея для тревожного шаблона 1</translation>
    </message>
    <message>
      <source>Display number for alarm template 2</source>
      <translation>Номер дисплея для тревожного шаблона 2</translation>
    </message>
    <message>
      <source>Display number for alarm template 3</source>
      <translation>Номер дисплея для тревожного шаблона 3</translation>
    </message>
    <message>
      <source>Display number to show pop-up</source>
      <translation>Номер монитора для перехода из всплывающих окон</translation>
    </message>
    <message>
      <source>Distance violation</source>
      <translation>Нарушение социальной дистанции</translation>
    </message>
    <message>
      <source>Door open / close state duration, (sec)</source>
      <translation>Время открытого/закрытого состояния двери,(сек)</translation>
    </message>
    <message>
      <source>E-mail account, created in Trassir</source>
      <translation>Учетная запись отправителя, созданная в Trassir</translation>
    </message>
    <message>
      <source>Enable logging</source>
      <translation>Логировнаие</translation>
    </message>
    <message>
      <source>Entrance in zones alarm (*simt, neuro)</source>
      <translation>Тревога при входе в зоны (*simt, neuro)</translation>
    </message>
    <message>
      <source>Escaping from zones alarm (*simt, neuro)</source>
      <translation>Тревога при выходе из зон (*simt, neuro)</translation>
    </message>
    <message>
      <source>Event subtype 'Controller: %1'</source>
      <translation>Подтип события 'Контроллер %1'</translation>
    </message>
    <message>
      <source>FTP folder on server</source>
      <translation>Папка на ftp сервере</translation>
    </message>
    <message>
      <source>FTP host</source>
      <translation>Хост</translation>
    </message>
    <message>
      <source>FTP passive mode</source>
      <translation>Пассивный режим FTP</translation>
    </message>
    <message>
      <source>FTP password</source>
      <translation>Пароль</translation>
    </message>
    <message>
      <source>FTP port</source>
      <translation>Порт</translation>
    </message>
    <message>
      <source>FTP user</source>
      <translation>Пользователь</translation>
    </message>
    <message>
      <source>Face detection alarm</source>
      <translation>Тревога при обнаружении лица</translation>
    </message>
    <message>
      <source>Face recognition alarm</source>
      <translation>Тревога по событиям распознавателя лиц</translation>
    </message>
    <message>
      <source>Fire or smoke appears</source>
      <translation>Тревога при появлении огня или дыма</translation>
    </message>
    <message>
      <source>Fire or smoke went out</source>
      <translation>Тревога при затухании огня</translation>
    </message>
    <message>
      <source>Folder name for saving shots</source>
      <translation>Имя папки для сохранения скриншотов</translation>
    </message>
    <message>
      <source>Gate PACS events</source>
      <translation>СКУД Gate</translation>
    </message>
    <message>
      <source>Group</source>
      <translation>Группа</translation>
    </message>
    <message>
      <source>Group not found: %s</source>
      <translation>Имя тревожной группы не найдено: %s</translation>
    </message>
    <message>
      <source>Hotkey for manual activation of operations</source>
      <translation>Клавиша для ручной активации операций</translation>
    </message>
    <message>
      <source>Ignore same events by period (sec)</source>
      <translation>Игнорирование идентичных событий за период (сек)</translation>
    </message>
    <message>
      <source>Ignore same events in period (sec)</source>
      <translation>Игнорирование идентичных событий за период (сек)(*neuro)</translation>
    </message>
    <message>
      <source>Ignoring identical events for a period, (sec)</source>
      <translation>Игнорирование идентичных событий за период, (сек)</translation>
    </message>
    <!-- Translated in 'EventsLoc' block
    <message>
      <source>Input Operations</source>
      <translation>Изменение состояния входа</translation>
    </message>
    -->
    <message>
      <source>Input high to low alarm</source>
      <translation>Тревога при размыкании тревожного входа</translation>
    </message>
    <message>
      <source>Input low to high alarm</source>
      <translation>Тревога при замыкании тревожного входа</translation>
    </message>
    <message>
      <source>Input state to make reaction</source>
      <translation>Состояние входа для работы</translation>
    </message>
    <!-- Translated in 'EventsLoc' block
    <message>
      <source>Intrusion Detected</source>
      <translation>Вторжение в зону</translation>
    </message>
    -->
    <message>
      <source>Intrusion detection alarm (SMART event from camera)</source>
      <translation>Тревога при вторжении в зону (SMART событие с камеры)</translation>
    </message>
    <message>
      <source>Item abandoned alarm</source>
      <translation>Тревога при появлении оставленного предмета</translation>
    </message>
    <message>
      <source>Key found</source>
      <translation>Ключ найден</translation>
    </message>
    <message>
      <source>Mail recipient list separated by comma</source>
      <translation>Список получателей через запятую</translation>
    </message>
    <message>
      <source>Make operations with PACS</source>
      <translation>Выполнить операции с точкой доступа СКУД</translation>
    </message>
    <message>
      <source>Make operations with outputs</source>
      <translation>Выполнить операции с тревожными выходами</translation>
    </message>
    <message>
      <source>Make reactions for all events</source>
      <translation>Реагировать на все события</translation>
    </message>
    <message>
      <source>Make reactions for event</source>
      <translation>Реагировать на событие</translation>
    </message>
    <!-- Translated in 'EventsLoc' block
    <message>
      <source>Max count vehicles</source>
      <translation>Детектировано максимальное количество автомобилей</translation>
    </message>
    -->
    <message>
      <source>Minimal compliance percentage in recognition</source>
      <translation>Минимальный процент соответствия</translation>
    </message>
    <message>
      <source>Motion detection alarm</source>
      <translation>Тревога при появлении движения</translation>
    </message>
    <message>
      <source>Multiple servers with the same name were found: %s</source>
      <translation>Найдено несколько серверов с одинаковым именем: %s</translation>
    </message>
    <message>
      <source>Neuro border crossing</source>
      <translation>Пересечение границы нейродетектора</translation>
    </message>
    <message>
      <source>Number of bicycle for alarm</source>
      <translation>Количество велосипедов для возбуждения тревоги</translation>
    </message>
    <message>
      <source>Number of people for alarm</source>
      <translation>Количество людей для возбуждения тревоги</translation>
    </message>
    <message>
      <source>Number of vehicle for alarm</source>
      <translation>Количество автомобилей для возбуждения тревоги</translation>
    </message>
    <message>
      <source>Numbers to send SMS messages(79999999999)</source>
      <translation>Номера, на которые должны приходить смс(79999999999)</translation>
    </message>
    <message>
      <source>Object size alarm (*simt)</source>
      <translation>Тревога по размеру объекта (*simt)</translation>
    </message>
    <message>
      <source>Object speed alarm (*simt)</source>
      <translation>Тревога по скорости объекта (*simt)</translation>
    </message>
    <message>
      <source>Object track length alarm (*simt)</source>
      <translation>Тревога по длине трека объекта (*simt)</translation>
    </message>
    <message>
      <source>Online shot</source>
      <translation>Скриншот с потока камеры</translation>
    </message>
    <message>
      <source>Only one screenshot per period (sec)</source>
      <translation>Не более одного скриншота с канала за период, сек</translation>
    </message>
    <message>
      <source>Only sensors alarm</source>
      <translation>Тревога только по датчикам</translation>
    </message>
    <message>
      <source>Operation type</source>
      <translation>Тип работы</translation>
    </message>
    <message>
      <source>Orion disabled</source>
      <translation>Orion disabled</translation>
    </message>
    <message>
      <source>Orion events alarm</source>
      <translation>Тревога по событиям Orion</translation>
    </message>
    <message>
      <source>Other</source>
      <translation>Другие параметры</translation>
    </message>
    <message>
      <source>PACS name</source>
      <translation>Название точки доступа СКУД</translation>
    </message>
    <message>
      <source>PACS type</source>
      <translation>Тип СКУД</translation>
    </message>
    <message>
      <source>Pass happened</source>
      <translation>Проход состоялся</translation>
    </message>
    <message>
      <source>Password or MD-5 hash in lowercase</source>
      <translation>Пароль или MD5-хеш пароля в нижнем регистре</translation>
    </message>
    <message>
      <source>People detected (SMART event from camera)</source>
      <translation>Обнаружены люди (событие с камеры)</translation>
    </message>
    <message>
      <source>Person</source>
      <translation>Персона</translation>
    </message>
    <message>
      <source>Person with fever</source>
      <translation>Тревога при превышении температуры</translation>
    </message>
    <message>
      <source>Person without a mask</source>
      <translation>Человек без маски</translation>
    </message>
    <message>
      <source>Person without helmet</source>
      <translation>Обнаружен человек без каски</translation>
    </message>
    <message>
      <source>Person without uniform</source>
      <translation>Обнаружен человек без спецодежды</translation>
    </message>
    <message>
      <source>Playback in archive</source>
      <translation>Открыть момент в архиве</translation>
    </message>
    <message>
      <source>Popup duration</source>
      <translation>Время отображения всплывающего окна</translation>
    </message>
    <message>
      <source>React for bicycles</source>
      <translation>Реагировать на велосипеды</translation>
    </message>
    <message>
      <source>React for people</source>
      <translation>Реагировать на людей</translation>
    </message>
    <message>
      <source>React for vehicle</source>
      <translation>Реагировать на автомобили</translation>
    </message>
    <message>
      <source>Reactions on objects presence in neuro zones</source>
      <translation>Реакция на нахождение объекта в зоне</translation>
    </message>
    <message>
      <source>SIMT detector alarm</source>
      <translation>Тревога по детектору SIMT/ нейродетектору</translation>
    </message>
    <message>
      <source>SIP code</source>
      <translation>Код SIP</translation>
    </message>
    <message>
      <source>SIP number</source>
      <translation>Номер SIP</translation>
    </message>
    <message>
      <source>SMS service login</source>
      <translation>Логин</translation>
    </message>
    <message>
      <source>Sabotage alarm</source>
      <translation>Тревога по событиям "Саботаж"</translation>
    </message>
    <message>
      <source>Save screenshot in screenshot folder</source>
      <translation>Сохранить снимок локально</translation>
    </message>
    <message>
      <source>Schedule for running the script</source>
      <translation>Расписание для работы скрипта</translation>
    </message>
    <message>
      <source>Screenshot of the sub-stream (experimental)</source>
      <translation>Скриншот субпотока (экспереминтальная функция)</translation>
    </message>
    <message>
      <source>Select PACS name</source>
      <translation>Необходимо указать название точки доступа</translation>
    </message>
    <message>
      <source>Select a server with persons db (Face recognizer section)</source>
      <translation>Необходимо выбрать сервер с базой лиц. (В разделе 'Распознаватель лиц')</translation>
    </message>
    <message>
      <source>Selected template not found %s</source>
      <translation>Выбранный шаблон не найден %s</translation>
    </message>
    <message>
      <source>Send SMS notification</source>
      <translation>Отправить уведомление по SMS</translation>
    </message>
    <message>
      <source>Send cloud alarm by token</source>
      <translation>Отправить тревогу по токену</translation>
    </message>
    <message>
      <source>Send code to SIP (server only)</source>
      <translation>Отправить код на SIP (только на сервере)</translation>
    </message>
    <message>
      <source>Send notification to e-mail</source>
      <translation>Отправить уведомление на e-mail</translation>
    </message>
    <message>
      <source>Send screen to FTP</source>
      <translation>Отправить снимок по FTP</translation>
    </message>
    <message>
      <source>Send screen to Telegram (only on server)</source>
      <translation>Снимок на Telegram (только на сервере)</translation>
    </message>
    <message>
      <source>Send screen to e-mail</source>
      <translation>Отправить снимок на e-mail</translation>
    </message>
    <message>
      <source>Server with name %s could not be found</source>
      <translation>Сервер с именем %s не найден</translation>
    </message>
    <message>
      <source>Server with the necessary folders of persons database</source>
      <translation>Сервер с нужными папками базы персон (группами)</translation>
    </message>
    <message>
      <source>Shot storage time (days)</source>
      <translation>Время хранения скриншотов, дней</translation>
    </message>
    <message>
      <source>Shot time correction ('-' - before, '+' - after)(ms)</source>
      <translation>Кор. времени шота ('-' - до события, '+' - после), миллисекунд</translation>
    </message>
    <message>
      <source>Shots with figures</source>
      <translation>Скриншоты с фигурами</translation>
    </message>
    <message>
      <source>Show channel</source>
      <translation>Отобразить канал</translation>
    </message>
    <message>
      <source>Show channel with alarm</source>
      <translation>Включить вывод канала на отображение</translation>
    </message>
    <message>
      <source>Show channel,Playback in archive</source>
      <translation>Отобразить канал,Открыть момент в архиве</translation>
    </message>
    <message>
      <source>Show pop-up</source>
      <translation>Вывести всплывающее окно</translation>
    </message>
    <message>
      <source>Show text message</source>
      <translation>Отображать текстовое сообщение</translation>
    </message>
    <message>
      <source>Sigur events alarm</source>
      <translation>Тревога по событиям Sigur</translation>
    </message>
    <message>
      <source>Sound detection alarm</source>
      <translation>Тревога при появлении звука</translation>
    </message>
    <message>
      <source>Sound file name</source>
      <translation>Название звукового файла</translation>
    </message>
    <message>
      <source>Sound notification</source>
      <translation>Проиграть звуковое оповещение</translation>
    </message>
    <message>
      <source>Specified E-mail account not found</source>
      <translation>Учетная запись e-mail в Trassir не задана</translation>
    </message>
    <message>
      <source>Specify alarm group name</source>
      <translation>Укажите имя тревожной группы</translation>
    </message>
    <message>
      <source>Specify aruco codes</source>
      <translation>Необходимо указать аруко коды для работы</translation>
    </message>
    <message>
      <source>Specify borders in section 'Borders' for reactions</source>
      <translation>Необходимо указать границы в разделе 'Границы для реакции'!</translation>
    </message>
    <message>
      <source>Specify person name</source>
      <translation>Персона не выбрана</translation>
    </message>
    <message>
      <source>Specify recipient(s) e-mail(s) separated by comma</source>
      <translation>Получатели почтовых уведомлений не заданы</translation>
    </message>
    <message>
      <source>Specify zones names</source>
      <translation>Необходимо указать имена зон для работы</translation>
    </message>
    <message>
      <source>Successful detections, % (*long-lasting)</source>
      <translation>Доля удовл. детекций, % (*продл. набл.)</translation>
    </message>
    <message>
      <source>Text message showing duration(sec)</source>
      <translation>Длительность отображения текcтового сообщения(сек)</translation>
    </message>
    <message>
      <source>The SIP code can only be sent on the server</source>
      <translation>Передача SIP кода возможна только на сервере!</translation>
    </message>
    <message>
      <source>The appearance of an object in the neuro zone</source>
      <translation>Появление объекта в зоне нейродетектора</translation>
    </message>
    <message>
      <source>The controller is disabled</source>
      <translation>Контроллер отключен</translation>
    </message>
    <message>
      <source>The controller is enabled</source>
      <translation>Контроллер подключен</translation>
    </message>
    <message>
      <source>The display duration of the channel in alarm template (sec)</source>
      <translation>Длительность отображения канала в тревожном шаблоне (сек)</translation>
    </message>
    <message>
      <source>The time of the open / closed state of the door must be in the range [1, 3600] sec</source>
      <translation>Время открытого/закрытого состояния двери должно быть в диапазоне [1, 3600] сек</translation>
    </message>
    <message>
      <source>The type of work for detection in zone</source>
      <translation>Тип работы для детекции в зоне</translation>
    </message>
    <message>
      <source>The type of work should be '%s' or '%s'</source>
      <translation>Тип работы должен быть '%s' или '%s'</translation>
    </message>
    <message>
      <source>There can only be one server with a database of persons</source>
      <translation>Сервер с базой лиц может быть только один</translation>
    </message>
    <message>
      <source>Time of observation before the alarm (*long-lasting), sec</source>
      <translation>Время наблюдения перед тревогой (*продл. набл.), сек</translation>
    </message>
    <message>
      <source>Time, spent by object in zone, before alarm(sec)</source>
      <translation>Время нахождения объекта в зоне перед тревогой(сек)</translation>
    </message>
    <!-- Translated in 'FaceRecognizerLoc' block
    <message>
      <source>Unrecognized person</source>
      <translation>Неопознанное лицо</translation>
    </message>
    -->
    <message>
      <source>User Telegram id</source>
      <translation>Telegram id пользователя</translation>
    </message>
    <message>
      <source>Voron events</source>
      <translation>События системы BOPOH</translation>
    </message>
    <message>
      <source>Working channels</source>
      <translation>Каналы в работе</translation>
    </message>
    <message>
      <source>Working servers</source>
      <translation>Серверы в работе</translation>
    </message>
    <message>
      <source>You must specify channels with face recognition in the Working channels field</source>
      <translation>Необходимо указать каналы с распознавателем лиц в поле 'Каналы в работе'</translation>
    </message>
    <message>
      <source>You must specify the SIP code</source>
      <translation>Необходимо указать SIP код для отправки!</translation>
    </message>
    <message>
      <source>You must specify the SIP number</source>
      <translation>Необходимо указать номер SIP!</translation>
    </message>
    <message>
      <source>You must specify the server (s) from which the channels are used</source>
      <translation>Необходимо указать сервер (-ы) с которых используются каналы</translation>
    </message>

    <message>
      <source>Crossing SIMT border</source>
      <translation>Пересечение границ SIMT</translation>
    </message>

     <message>
      <source>SIMT events in the selected zones</source>
      <translation>События SIMT в выбранных зонах</translation>
    </message>

    <message>
      <source>Spam filter</source>
      <translation>Спам фильтр</translation>
    </message>

    <message>
      <source>Zone names to check (for events in zone)</source>
      <translation>Зоны для работы (событие в зоне simt)</translation>
    </message>
    <message>
      <source>Zones names for detections (for all channels)</source>
      <translation>Зоны для детектирования (общий список для всех каналов)</translation>
    </message>
    <message>
      <source>alert in a zone</source>
      <translation>тревога в зоне</translation>
    </message>
    <message>
      <source>automatic alarm confirmation</source>
      <translation>автоматическое подтверждение тревоги</translation>
    </message>
    <message>
      <source>close thе door</source>
      <translation>закрыть</translation>
    </message>
    <message>
      <source>closed</source>
      <translation>закрыто</translation>
    </message>
    <message>
      <source>immediate</source>
      <translation>немедленная реакция</translation>
    </message>
    <message>
      <source>long-lasting</source>
      <translation>продолжительное наблюдение</translation>
    </message>
    <message>
      <source>manual alarm confirmation</source>
      <translation>ручное подтверждение тревоги</translation>
    </message>
    <message>
      <source>no</source>
      <translation>нет</translation>
    </message>
    <message>
      <source>open the door</source>
      <translation>открыть дверь</translation>
    </message>
    <message>
      <source>opened</source>
      <translation>разомкнут</translation>
    </message>
    <message>
      <source>the zone is unguarded</source>
      <translation>зона снята с охраны</translation>
    </message>
    <message>
      <source>zone failure</source>
      <translation>неисправность зоны</translation>
    </message>
    <message>
      <source>zone guarded</source>
      <translation>зона поставлена на охрану</translation>
    </message>

    <!-- NeuroLoc -->
    <message>
      <source>Bicycle</source>
      <translation>Велосипед</translation>
    </message>
    <message>
      <source>Border</source>
      <translation>Граница</translation>
    </message>
    <message>
      <source>Event time</source>
      <translation>Время события</translation>
    </message>
    <message>
      <source>Last detection quantity</source>
      <translation>Количество в последней детекции</translation>
    </message>
    <message>
      <source>Level to react</source>
      <translation>Уровень для реагирования</translation>
    </message>
    <!-- Translated in 'Main' block
    <message>
      <source>Person</source>
      <translation>Персона</translation>
    </message>
    -->
    <message>
      <source>Vehicle</source>
      <translation>Автомобиль</translation>
    </message>
    <message>
      <source>Zone name</source>
      <translation>Имя зоны</translation>
    </message>

    <!-- PopupLoc -->
    <message>
      <source>Cancel</source>
      <translation>Отмена</translation>
    </message>
    <message>
      <source>Show event in archive</source>
      <translation>Открыть момент в архиве</translation>
    </message>

    <!-- SimtLoc -->
    <!-- Translated in 'GpioLoc' block
    <message>
      <source>Associated channel</source>
      <translation>Ассоциированный канал</translation>
    </message>
    -->
    <message>
      <source>Border name</source>
      <translation>Имя границы</translation>
    </message>
    <!-- Translated in 'NeuroLoc' block
    <message>
      <source>Zone name</source>
      <translation>Имя зоны</translation>
    </message>
    -->
    <message>
      <source>any</source>
      <translation>любое</translation>
    </message>

    <message>
      <source>Suspicious pose</source>
      <translation>Подозрительная поза</translation>
    </message>
    <message>
      <source>Suspicious pose</source>
      <translation>Подозрительная поза</translation>
    </message>

    <message>
      <source>Every time show a channel in the same cell</source>
      <translation>Зафиксировать ячейку для каждого канала при отображении в ТМ</translation>
    </message>

  </context>
</TS>